### ISSUE TITLE
Make it possible to delete files from the user interface

### ISSUE THREAD

**Issue by TwizzyDizzy** [Sonerezh/sonerezh#100]
Hi folks,

as I understand it, there is currently no way to delete a file from my library (except for deleting the complete song library).

There could be two different approaches:
1. deleting tracks from disk that disappeared physically from disk (by deleting it from the server - for example "rm filename.mp3") and then deleting that track from the song database. This would require two actions ( a) delete the file physically from disk, b) hitting the "update database" button in the user interface)
2. delete the track from the user interface and then let it be removed by the scheduler (as described in #97). On deleting the file from the interface, the track would be marked as "being to delete" (and would not appear in the user interface anymore) for the scheduler which would then delete it from the database forever and deleting the file phsyically from the disk. This interconnects with #98 - the part that describes the "referenced" songs that are to be deleted.

I would prefer to go with the latter approach.

Cheers
Thomas

**Comment by lGuillaume124** [comment]
These ideas are very interesting, we could be able to implement them with the metada edition features planned for 1.1.0 :)

**Comment by TwizzyDizzy** [comment]
Hi Guillaume,

yes, I think this would fit into that type of change.

**Comment by gs11** [comment]
See similar issue #129 and the fix in pull req #293

**Comment by gs11** [comment]
Please close issue, fixed in latest PR.
