### ISSUE TITLE
Legal implications of "listener" accounts, streaming, sharing and downloading

### ISSUE THREAD

**Issue by TwizzyDizzy** [Sonerezh/sonerezh#104]
Hi folks,

this is a rather non-technical issue.

**DISCLAIMER**: I do not advocate strong copyright laws and neither do I find sharing songs with my friends to be something that should be forbidden or restricted, but in times like these you unfortunately gotta think about such issues.

Back in the good old days, one would exchange with and copy tapes from friends. I think of sonerezh "listener"-accounts as being of no difference to just that (especially when downloading, see issue #17). Is streaming like downloading - that's a completely different topic by itself).

But what if I have like a hundred friends from my university that can listen and download my music?

With the content industry causing havoc anywhere they set foot this could be a legal issue pretty easily.

Of course, this is nothing your software is responsible for. It's my decision to share music with my friends **by the means of sonerezh** but I think by now you know what I'm talking about.

There should be some legal disclaimer to not stream/download copyright protected files.

Maybe there could even be some database flag, that allows the user to set a song/album to "don't stream, don't download". Maybe there could also be some setting which is not checked by default and doesn't allow sharing overall. If I then decide to officially brake "law", I check the button "FUCK COPYRIGHT - SHARING MEANS CARING!" and enable downloading/streaming overall.

Cheers
Thomas

**Comment by lGuillaume124** [comment]
Indeed, we could add a legal notice to be very clear. But I have always seen Sonerezh as a Wordpress like, but designed to manage your audio collection.

You can install a WordPress and use it to share illegal content and Worpress should not be prosecuted for that...

**Comment by TwizzyDizzy** [comment]
Hi Guillaume,

you are totally right. After having thought about it a bit more in detail I will close this issue.

Thanks for your reply anyway :)
