### ISSUE TITLE
The requested URL /sonerezh/install was not found on this server.

### ISSUE THREAD

**Issue by XelionXS** [Sonerezh/sonerezh#105]
I followed all the steps but i've this problem :/

The requested URL /sonerezh/install was not found on this server.

PS : I've already active rewrite module :

root@sd-24755:/var/www/html# a2enmod rewrite
Module rewrite already enabled
root@sd-24755:/var/www/html# service apache2 restart

**Comment by TwizzyDizzy** [comment]
Hi XelionXS,

you may run into the problem, that your override options may be disabled for either */* or something above */var/www/html*. In your virtual host configuration there may be something like

> \<Directory /var/www/html\>
>         Options +FollowSymLinks -Indexes -Multiviews
>         AllowOverride None
> \</Directory\>

Try changing it to

> \<Directory /var/www/html\>
>         Options +FollowSymLinks -Indexes -Multiviews
>         AllowOverride FileInfo
> \</Directory\>

and see, wether it works.

Also, make sure you have

> RewriteEngine on

in the relevant section of your vhost configuration.

Cheers
Thomas

**Comment by XelionXS** [comment]
That doesn't seem to work :/

This is my default.conf in /etc/apache2/sites-available/ :

<VirtualHost *:80>
    ServerName      sonerezh.xelion.fr
    DocumentRoot    /var/www/html/sonerezh/
    RewriteEngine on

    <Directory /var/www/html/sonerezh/>
        Options +FollowSymLinks -Indexes -Multiviews
        AllowOverride All

        # Apache 2.2.x
        <IfModule !mod_authz_core.c>
            Order Allow,Deny
            Allow from all
        </IfModule>

        # Apache 2.4.x
        <IfModule mod_authz_core.c>
            Require all granted
        </IfModule>
    </Directory>

    CustomLog   /var/log/apache2/sonerezh.xelion.fr-access.log "Combined"
    ErrorLog    /var/log/apache2/sonerezh.xelion.fr-error.log
</VirtualHost>

**Comment by TwizzyDizzy** [comment]
After having replicated your setup with the exact settings above I cannot confirm your issues.

Please do provide - as stated above - a "find /var/www" and the complete configuration file.

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
Hi @XelionXS,

did you fix your issue or do you still need help? If fixed, please close the issue, otherwise just provide me with the aforementioned information - I'd be glad to help.

Cheers
Thomas

**Comment by lGuillaume124** [comment]
According to @TwizzyDizzy it does not seem to be a Sonerezh issue :/
Is it normal that you don't have any `ServerName`attribute in your vhost?
Do the Apache error logs say something?

**Comment by lGuillaume124** [comment]
Any news since July. As it does not seem to be a Sonerezh issue, I close this one.
