### ISSUE TITLE
Nombres de musiques trop importante ?

### ISSUE THREAD

**Issue by CooperBarrett** [Sonerezh/sonerezh#106]
_English version below_

Salut,
Pour info, je suis sous Nginx
J'ai un problème avec l'importation de mes Musiques.
Mon dossier est organisé comme ceci : /home/user/Musiques/Artiste/Albums/Chansons
Lorsque je met mon mon dossier Musiques à importer (/home/user/Musiques/), il ne se passe rien et quand je vais dans sonerezh.domaine.fr/import, j'ai une erreur 502 Bad Gataway.
Alors que si je n'importe qu'un artiste (/home/user/Musiques/Artiste/), tout se passe correctement.
Pas de soucis en me rendant sur sonerezh.domaine.fr/import.
J'ai essayé avec des artistes ayant des caractères spéciaux, cela fonctionne.
J'en arrive à la conclusion que c'est à cause d'un trop grand nombre de dossiers mais sans en être sûr...
Est-ce quelqu'un a déjà eu ce problème et surtout est-ce que quelqu'un aurait la solution ?
Merci d'avance

---
Hi,
I'm using Nginx.
I have a problem during the import. My folders are organised as this : /home/user/Musiques/Artiste/Albums/Chansons
When I set this folder on Sonerezh's settings, anything happens when I go to sonerezh.domaine.fr/import and I get a 502 Bad Gateway Error.
I tried with band names containing special characters and it works.
So I think I have too many folders but I'm not very sure.
Does anyone already has this problem and has a solution?
Thanks.

**Comment by nodiscc** [comment]
@Kaoz52 is there anything relevant in your nginx logs/syslog?

**Comment by Kaoz52** [comment]
Ah si désolé, j'ai oublié de le mettre : 

2015/07/20 15:20:42 [error] 12245#12245: *11556 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 82.XXX.XXX.XX, server: music.domaine.fr, request: "GET /import?ajax=true HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "music.domaine.fr", referrer: "http://music.domaine.fr/settings"

J'ai masqué mon IP et modifié mon nom de domaine

**Comment by Kaoz52** [comment]
No ideas ?

**Comment by lGuillaume124** [comment]
Bonjour,
Pourrais-je vois votre server block Nginx svp ?

Pour connaître le nombre de dossier dans votre répertoire vous pouvez essayer : 
`````bash
find /home/user/Musiques/ -type d | wc -l
````
Chez moi j'en ai environ 3400.

----
Hello,
Can I see your Nginx server block please?

To know how many folders you have in your directory you can try:
`````bash
find /home/user/Musiques/ -type d | wc -l
````
I run Sonerezh with almost 3400 folders.

**Comment by Kaoz52** [comment]
Merci pour ta réponse, effectivement j'en ai moins que toi.
J' ai 2604 dossiers

Et voilà mon server Block :
```
server {
    listen 80;

    server_name music.domaine.fr;
    root /var/www/sonerezh/app/webroot;

    access_log /var/log/nginx/sonerezh.access.log;
    error_log /var/log/nginx/sonerezh.error.log;

    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    # Serve static images from resized folder
    location ~* \/([^\/]+_[0-9]+x[0-9]+\.[a-z]+) {
        try_files /img/resized/$1 /index.php?$args;
        expires 14d;
        add_header Cache-Control 'public';
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_index index.php;
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include /etc/nginx/fastcgi_params;
    }
}

```
Merci de ton aide

**Comment by Kaoz52** [comment]
Hello, 

I makes me revive my problem because I still have not found solutions ...
I do not really see where that can come!

Thanks for your help
-------------------------------------------------------------------------------------------------------------------------------------------
Bonjour, 

Je me permet relancer mon problème car je n'ai toujours pas trouvé de solutions...
Je ne vois pas vraiment d'où cela peut provenir ! 

Merci pour votre aide

**Comment by lGuillaume124** [comment]
Hello,
What do you have in /etc/nginx/nginx.conf please?
It may come from the fastcgi buffer size.

**Comment by Kaoz52** [comment]
Hi,

Thank you for your answer, here is my nginx.conf file:

```
user www-data;
worker_processes auto;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
    use epoll; # gestionnaire d'évènements epoll (kernel 2.6+)
}

http {
    include /etc/nginx/mime.types;
    default_type  application/octet-stream;

    access_log /var/log/nginx/access.log combined;
    error_log /var/log/nginx/error.log error;

    sendfile on;
    keepalive_timeout 15;
    keepalive_disable msie6;
    keepalive_requests 100;
    tcp_nopush on;
    tcp_nodelay off;
    server_tokens off;

    gzip on;
    gzip_comp_level 5;
    gzip_min_length 512;
    gzip_buffers 4 8k;
    gzip_proxied any;
    gzip_vary on;
    gzip_disable "msie6";
    gzip_types
        text/css
        text/javascript
        text/xml
        text/plain
        text/x-component
        application/javascript
        application/x-javascript
        application/json
        application/xml
        application/rss+xml
        application/vnd.ms-fontobject
        font/truetype
        font/opentype
        image/svg+xml;

    include /etc/nginx/sites-enabled/*.conf;
}
```

**Comment by lGuillaume124** [comment]
Hi,
Did you find a solution?

**Comment by Kaoz52** [comment]
Malheureusement non, j'ai un peu laissé tomber mes recherches ces derniers temps mais si tu as une solution ou un debut de réponse à mon problème, j'en serai ravi.

Dans tous les cas, merci de t'en inquiéter.

------------------------------------------------------------
Google Trad: 

Unfortunately not, I just dropped my research lately but if you have a solution or an answer to my problem early, I will be delighted.

In any case, thank you to worry about.
