### ISSUE TITLE
Replace avconv with ffmpeg

### ISSUE THREAD

**Issue by DavidVentura** [Sonerezh/sonerezh#107]
Debian is going back to defaulting ffmpeg, ubuntu likely will follow for the next release. Could you replace avconv with ffmpeg or at least check for any of them ?

**Comment by onny** [comment]
+1
ArchLinux doesn't provide avconv anymore

**Comment by tbeitter** [comment]
+1

**Comment by khromov** [comment]
+1

**Comment by lolop-lj** [comment]
+1

**Comment by geeromsm** [comment]
+1 (no ipkg package for aconv on synology, but there is one for ffmpeg).
I use Sonerezh on Synology, it's great.

**Comment by MightyCreak** [comment]
It's already the case isn't it?

https://github.com/Sonerezh/sonerezh/blob/master/app/Controller/SettingsController.php#L98

**Comment by geeromsm** [comment]
Well, then the error messages need an update:

"Automatic tracks conversion
The command 'avconv' is not available. Sonerezh cannot convert your tracks."
