### ISSUE TITLE
Sonerezh does not work on iPhone 4

### ISSUE THREAD

**Issue by tomcodes** [Sonerezh/sonerezh#108]
Here are some issues when trying to use Sonerezh on the iPhone 4:
- Playback does not work
- Keeps logging out

I went to html5test.com and the audio section says that I don't have the following:
- Ogg Vorbis Support
- Ogg Opus Support
- WebM with Vorbis support
- WebM with Opus support

The output destination is mp3, 320 kbps. Thanks in advance!

**Comment by lGuillaume124** [comment]
Hello,
iOS is not supported yet.

**Comment by tomcodes** [comment]
Hello,
Thanks for your reply. May I ask what would be needed to make it work on a mobile browser?
Thank you.

**Comment by lGuillaume124** [comment]
It works for me on iPad Mini 2 / iOS 9.1 / Safari 0o

An iOS native app will be developed when the API will be ready.
