### ISSUE TITLE
Add "Added on" date to songs

### ISSUE THREAD

**Issue by DavidVentura** [Sonerezh/sonerezh#109]
Could you add the date the songs were added and some way to sort the songs by when they were added? So I can listen to the latest songs that I have added to my library

**Comment by lGuillaume124** [comment]
Hello,
I'd like to have this feature too ;)

**Comment by DavidVentura** [comment]
Development seems stalled. Is this so or are you actually working on 1.0 stuff but not pushing the changes? I'd like to start working on some of the features but I'm not sure if they're being worked on already

**Comment by lGuillaume124** [comment]
Indeed, we are writing our master degree dissertation and we will be back in September :)

**Comment by lGuillaume124** [comment]
What about something like that on the albums view ("Ajoutés récemment" means "Recently added")?

![selection_012](https://cloud.githubusercontent.com/assets/3330841/12079386/6f6aa41a-b237-11e5-8432-f71d32416766.png)

**Comment by lGuillaume124** [comment]
In fact we already have a "created" column in the database table. It should not be difficult to implement this kind of feature.

**Comment by lGuillaume124** [comment]
I consider this issue as closed because the "added on" field is already implemented in the database. We plan to add many filters on each view in the future releases, but not for 1.0.0 (see [the roadmap](https://roadmap.sonerezh.bzh/b/eCuz4jyhwjmxpxX8C/sonerezh-roadmap/q7sHugYTWq8ySZZro)).
