### ISSUE TITLE
Keep going at the end of a song

### ISSUE THREAD

**Issue by dadall** [Sonerezh/sonerezh#11]
When a song ends, the next one doesn't start. Can you add this feature ?

**Comment by lGuillaume124** [comment]
Hi,

Yes, we know that the default view needs to be improved. It will, don't worry.

**Comment by dadall** [comment]
That was just a question, thanks ! :)

**Comment by lGuillaume124** [comment]
We improve the queue management since 0.9.0. Sonerezh can now read entire albums, bands or playlists. So I think we can close this issue :)
