### ISSUE TITLE
Problème page des albums

### ISSUE THREAD

**Issue by lgeneix** [Sonerezh/sonerezh#111]
Hi,

Je rencontre un petit soucis avec la version 1.0.0-beta. Lorsque je lance la page albums celle-ci charge sans fin jusqu'au timeout du serveur (ou obligé de redémarrer apache). Après recherche cela vient de l'action albums du SongsController et plus particulièrement de l'utilisation du helper Paginator.
Je n'avait pas ce problème avec la version 0.9.0-beta qui n'utilisait pas le Paginator.

Aucune erreur en mode Debug ni dans les logs apache.

Est-ce quelqu'un a déjà rencontré ce problème ?

**Comment by rizys** [comment]
Je rencontre exactement le même problème que toi en installant avec une bdd mysql et - lorsque je clique sur l'onglet album - le processus mysql tourne à plein régime sans fin. En réduisant ma médiathèque à seulement une dizaine d'albums, j'obtiens finalement le résultat escompté mais après une longue attente.

Maintenant j'utilise une bdd sqlite3 et la page album ne fonctionne carrément plus (la page en cours se recharge totalement)... Au moins je ne rencontre pas d'erreur et ne sature pas le serveur ;-)

Une petite précision, tout cela tourne sur un nas DNS-320 pas bien puissant ! Je comptais donc attendre de tester sur une vraie config pour en parler mais puisque la question est posée...

Beau projet en tout cas :+1:

**Comment by lgeneix** [comment]
J'ai d'autres solutions hebergées et tout tourne nickel, j'ai aussi essayé d'augmenté la taille des buffer MySQL et php mais rien n'y fait. Je pense qu'il vaut mieux regarder du coté des requètes de cakePHP afin de les optimiser.

**Comment by rizys** [comment]
Comme toi, le paramétrage de php et de mysql ne m'ont été d'aucun secours...

**Comment by dadall** [comment]
Je re-up cette demande. Ça ne serait pas possible de charger la liste des albums et seulement après les chansons qui y sont attachées ? 
Mon petit serveur ne supporte pas non plus la page album :(

**Comment by lGuillaume124** [comment]
Il semblerait qu'une régression soit apparue dans le commit 9b79c0c. J'ai ajouté une condition avec une sous-requête sur la requête SQL effectuée et les petites configurations n'ont pas l'air d'apprécier...

It seems that I introduced a regression in 9b79c0c. I added a condition with a subquery in the SQL query and apparently the small servers don't like it...

**Comment by lGuillaume124** [comment]
J'ai regardé rapidement, je pense qu'il manque un index sur la colonne album de la tbale songs. Pourriez-vous créer cet index et réessayer ?
```sql
CREATE INDEX `albums` ON `songs` (`album`);
```
Je vais continuer de chercher mais je pense avoir une bonne piste là.

**Comment by cgx** [comment]
Ça semble régler le problème de mon côté. Merci!

**Comment by lGuillaume124** [comment]
Vous pouvez aussi ajouter un index sur la colonne band, ça allègera la vue artists :
```sql
CREATE INDEX `bands` ON `songs` (`band`);
```

**Comment by dadall** [comment]
Merci !
