### ISSUE TITLE
1.0-beta is absurdly broken

### ISSUE THREAD

**Issue by DavidVentura** [Sonerezh/sonerezh#113]
Is this only me? I've just jumped from 0.9 to 1.0-beta and I get a mysql process frequently on 100% on one of the cores of my server. Adding an album to queue adds the entire database to the queue (>3k songs).. and so on.

**Comment by rizys** [comment]
It's not only you. Try this : https://github.com/lgeneix/sonerezh/commit/1adbc1c376df2e402264c8a8c6769b833ef6bd98 ! It's working for me :)

**Comment by DavidVentura** [comment]
Nope. Adding any song adds the entire database to the queue

**Comment by rizys** [comment]
Right, not the same problem...

**Comment by DavidVentura** [comment]
I thought it qualified as the same as "Adding an album to queue adds the entire database to the queue (>3k songs).. and so on." 

Does that commit fixthe 100% mysql process?

**Comment by rizys** [comment]
This fix repairs the 100% mysql process when you click on the album page for small machines but your adding trouble persists.

**Comment by lGuillaume124** [comment]
Hi all,
We take note of your suggestions, but as you can seen we don't commit anymore since the end of June because atomiix and I are redacting our master degree dissertation and won't be available until Sept. 15th.

After that, we have many improvements to be added :)
