### ISSUE TITLE
Problème passWord

### ISSUE THREAD

**Issue by ClementCS** [Sonerezh/sonerezh#115]
salut!

Petit bug sur la sécurité du passWord!
En passant par l'URL "XXXXX /users/edit/2" il est possible de "changer"  le MDP de l'utilisateur et se log sur son compte.
j'ai ainsi peu prendre le compte de l'admin et acceder aux fonctionalités qui lui sont dédiées!

Merci pour votre taf :)

**Comment by lgeneix** [comment]
J'ai effectué le test et en tant qu'utilisateur simple (listener) et lorsqu'on passe dans l'url l'URL "XXXXX /users/edit/<id_d'un_compte_admin>" on est bien redirigé vers l'accueil de l'appli donc on ne peut modifier le password d'un admin.
Es-tu bien sur la 1.0.0beta ?

**Comment by SyBen** [comment]
Bug reproduit sur la version principale (un utilisateur normal peut changer le mdp d'un admin), version 0.9

**Comment by ClementCS** [comment]
Salut, je refait un test dans la journée! Je ne connais pas la version (ce n'est pas moi qui ai fait l'instal).

Pour nos configuration :
------------
Téléchargée ici il y a genre un mois :
https://github.com/Sonerezh/sonerezh/archive/master.zip"
--------------
Les droits ont été modifié comme ça :
chown -R www-data:www-data /var/www/sonerezh && chmod -R 775 /var/www/sonerezh

Le serveur web utilize est nginx et qu’il est configuré comme ça:
server {
        listen 81;
        server_name _;
        root        /var/www/sonerezh/app/webroot;
        index index.php;
        charset utf-8;

        location / {
                try_files $uri $uri/ /index.php?$args;
        }

        # Serve static images from resized folder
        location ~* \/([^\/]+_[0-9]+x[0-9]+\.[a-z]+) {
                try_files /img/resized/$1 /index.php?$args;
                expires 14d;
                add_header Cache-Control 'public';
        }

        location ~ \.php$ {
                try_files $uri =404;
                fastcgi_index index.php;
                fastcgi_pass unix:/var/run/php5-fpm.sock;
                include /etc/nginx/fastcgi_params;
    }
}
----------------------

Quand je passe en listener et passe dans l'URL  XXXXX /users/edit/id_d'un_compte_admin je tombe directement sur l'edit du compte! je peu ensuite changer le mdp etc..

![sans titre](https://cloud.githubusercontent.com/assets/11422114/9219120/e1bdee94-40d8-11e5-8793-9be4612fe218.png)

**Comment by lgeneix** [comment]
La branche master de github correspont à la version 0.9.0-beta, le problème de sécurité du password était connu sur cette version et à été corrigé dans la 1.0.0-beta, donc je te conseille de passer à cette dernière afin d'avoir les derniers correctifs.

**Comment by ClementCS** [comment]
OK super! 

Je fais la remponté à notre admin !

Merci pour tout :)
