### ISSUE TITLE
Songs are duplicated when i attempt to update database

### ISSUE THREAD

**Issue by kingdave** [Sonerezh/sonerezh#122]
Hello,
at first, this project is the best what i've found to manage my music collection - thanks! But. There's one problem. When I attempt to use "Update database" button, it loads everything and then I see every song twice (except the newly added ones). Do you know, what should be the reason of this bug? Can you fix it? 
I also experience one more problem - sometimes (usually after the DB update) the Artists list remains not updated, so I must use F5 and then the new version shows up (with the doubled songs of course unfortunately). What to do with this problem?
Thanks!

**Comment by kingdave** [comment]
Eh? I can't even understand that. Now I am uploading second album to the server. And when I click Update, the first album doesn't double - just the new (second) one. ???

**Comment by tbeitter** [comment]
I have similar problems with a fresh db import (after a DB reset). Some albums get dozens of duplicated file entries, some just show the path to the file. There seem to be some issues with the import.

**Comment by lGuillaume124** [comment]
Could you describe the bug step by step please? I'd like to reproduce it. Screenshots are welcome too.

**Comment by matunixe** [comment]
Hello I have the same problem here.
1. I upload a new album of Betraying The Martyrs to my repo
2. I Reset the db
3. I clear the cache
4. I update the db
5. I get 468 songs in Sonerezh...

I make some screenshots for you:
##Updating the db
![update](http://pix.unixcorn.org/image/1450455191/original.jpg)
##Looking at the "Artists" section
![artists](http://pix.unixcorn.org/image/1450455308/original.jpg)
768 songs for 2 albums...
##Checking my repository
![repo](http://pix.unixcorn.org/image/1450455420/original.jpg)
There is no problem with my files.

**Comment by lGuillaume124** [comment]
Interesting! Could you sent us "01 Ad Astra.mp3" please? I can't reproduce this issue with my music collection :/

**Comment by neilgrover** [comment]
I am experiencing the same bug. All my songs are duplicated. I really like Sonerezh! This is the only issue I'm having. Not sure how to help. I'm using PostgreSQL on Linux.

**Comment by fcharlier** [comment]
Hi, I got the same error few days ago, and noticed it happens when maximum execution time is exceeded.

Look for errors in you php logs.
```
 PHP Fatal error:  Maximum execution time of 30 seconds exceeded in […]/sonerezh/app/Vendor/Getid3/module.audio.mp3.php on line XXX
```

Fixed the problem by increasing ```max_execution_time``` in the ```php.ini``` file.

**Comment by neilgrover** [comment]
Hrm.. I don't see a timeout error in my logs. I also don't think my music collection is large enough to cause the import to hit the 30 second limit. I tried bumped my max_execution_time to 120 seconds (and verified that the setting was applied), then did a "database reset" followed by an "update database" ... I still wound up with duplicate songs.

**Comment by lGuillaume124** [comment]
Hey guys, after many hours tearing my hair out, I think I've found a solution. The fix is on the dev branch so if you want to test it you can do:

```bash
git fetch
git checkout -b local_test e0b6f86
```
The import function is one of the first one written in the Sonerezh project and dig into it make me realize that it needs a complete refactoring, with error management and debug logs...

**Comment by neilgrover** [comment]
Just updated to your dev branch... and... no more duplicates!

I only have mp3 files.

I'm a happy camper now. Many thanks for you hard work!
