### ISSUE TITLE
Demo doesn't play songs (linux firefox)

### ISSUE THREAD

**Issue by aerth** [Sonerezh/sonerezh#124]
Doesn't play with Firefox on Arch Linux. Demo player works with Firefox on Windows

No error message, just keeps skipping song. Works fine using windows.

**Comment by lGuillaume124** [comment]
Hello,
Indeed, Archlinux needs some codecs to run Sonerezh on Firefox. Issue #94 :

Tangeek42 installed gst-libav and gst-plugins-good. You can find help here: https://wiki.archlinux.org/index.php/Firefox#Multimedia_playback

**Comment by tbeitter** [comment]
Same for my own v1.0.0 instance, gst-libav and gst-plugins-good fixed it. Thanks!
