### ISSUE TITLE
artists view - order album tracks by track number (ogg), split into different CDs

### ISSUE THREAD

**Issue by tbeitter** [Sonerezh/sonerezh#128]
1. I do not recognise which way the tracks of an ogg encoded album are sorted right now, but I would prefer to see it done by the track numbers. These works for mp3 files. (maybe related to #130)

2. If the album got more than one disc it would be nice if this would be represented by the view. maybe it could be splitted into the existing columns.

(tested with v0.9.0-beta / v1.1.0)

Best,
Til

**Comment by lGuillaume124** [comment]
These are OGG files. We missed some tags in the import process, thanks for your contribution

![selection_009](https://cloud.githubusercontent.com/assets/3330841/10711535/aea54568-7a7e-11e5-9380-e4bd51edb196.png)
