### ISSUE TITLE
database update - remove deleted files from database

### ISSUE THREAD

**Issue by tbeitter** [Sonerezh/sonerezh#129]
Right now deleted files will not be removed from the sonerezh database.

I just noticed I got duplicated tracks due to a duplicated folder on my filesystem. So I removed that directory, but on sonerezh I still see these doubled files for that album and the database still contains those wrong and meanwhile deleted files.

**Comment by lGuillaume124** [comment]
Yes, you can only synchronize the database in one way for the moment. This should be improved when we will work on the metadata edition capabilities.

**Comment by hurlebouc** [comment]
Hi!
Even if it is not possible automatically for now, is there any way to manually remove deleted tracks from sonerezh library?

**Comment by lGuillaume124** [comment]
Hi @hurlebouc 
Yes, in the database, into the table named ```songs```. All the stuff is here.

**Comment by ltGuillaume** [comment]
https://github.com/ltGuillaume/sonerezh/commit/6d0ffa7da42730be1932b905db79c0f26265ebb9

**Comment by gs11** [comment]
See pull request #293 for a fix. Please review

**Comment by gs11** [comment]
PR #293 merged, please close the issue.
