### ISSUE TITLE
track tagging broken with ogg files

### ISSUE THREAD

**Issue by tbeitter** [Sonerezh/sonerezh#130]
If I add an album as tagged mp3 it will be imported fine, all track informations, especially album and track artists, is presented correctly (and in a really nice way I until now only saw with sonerezh, thanks for that!)

![tagging_mp3](https://cloud.githubusercontent.com/assets/756334/10452592/5c95df8e-71a6-11e5-819c-9159da7ca35f.png)

If I add the same album as ogg with identically tags, the track informations get mixed. Every "track artists" now is stored as an own album with one/several tracks. Album cover art will not be found that way, too. (As these albums do not exist):

![tagging_ogg](https://cloud.githubusercontent.com/assets/756334/10452614/622cfd4c-71a6-11e5-95b5-9ac68bf53c96.png)

(right now I only checked mp3 and ogg, flac has to be tested, too)

(tested with v0.9.0-beta / v1.1.0)

**Comment by lGuillaume124** [comment]
Could you sent us one of your files in both formats please?

**Comment by lGuillaume124** [comment]
These are OGG files. We missed some tags in the import process, thanks for your contribution.

![selection_009](https://cloud.githubusercontent.com/assets/3330841/10711535/aea54568-7a7e-11e5-9380-e4bd51edb196.png)

**Comment by tbeitter** [comment]
Thanks! In general that works now. But I still have some probs importing my whole database. Albums which are broken in the big import are fine if imported alone. (=DB path set to this specific album). This seems to happen will all kind of files, mp3 and ogg, so I think this issue is done, but another one is needed.
