### ISSUE TITLE
Upnp/DLNA Player

### ISSUE THREAD

**Issue by jeromeLB** [Sonerezh/sonerezh#132]
I would appreciate if sonerezh was a upnp/dlna player
It should be a great feature !

**Comment by nodiscc** [comment]
@jeromeLB check out http://djmount.sourceforge.net/. The mounted uPnP server should appear as a normal filesystem for sonerezh

**Comment by lGuillaume124** [comment]
Hello @jeromeLB,
This feature is not in the roadmap, and not a priority for the moment sorry :/
