### ISSUE TITLE
1.0.0-beta not working

### ISSUE THREAD

**Issue by tbeitter** [Sonerezh/sonerezh#133]
If I use 1.0.0-beta from git I only see the blue navbar, but do not get any installer. Same happens when I use a working database config. Debug shows the following error in the blue navbar:

"Fatal error: Class 'AuthComponent' not found in /srv/http/sonerezh-git/app/View/Layouts/default.ctp on line 51"

tested with firefox and chromium

**Comment by tbeitter** [comment]
I managed to solve this by manually seting date.timezone in my php.ini

Now I can see the install dialog, but I am not able to save my settings:

Notice (8): Undefined index: id [APP/Model/User.php, line 148]

**Comment by tbeitter** [comment]
it seems this is related to the earlier issue, too:

```
2015-11-04 09:59:37 Error: Fatal Error (1): Class 'AuthComponent' not found in [/srv/http/sonerezh-git/app/View/Layouts/default.ctp, line 51]
2015-11-04 09:59:37 Error: [FatalErrorException] Class 'AuthComponent' not found
Request URL: /install
Stack Trace:
#0 /srv/http/sonerezh-git/lib/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Class 'AuthComp...', '/srv/http/soner...', 51)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'AuthComp...', '/srv/http/soner...', 51, Array)
#2 /srv/http/sonerezh-git/lib/Cake/Core/App.php(931): call_user_func('ErrorHandler::h...', 1, 'Class 'AuthComp...', '/srv/http/soner...', 51, Array)
#3 /srv/http/sonerezh-git/lib/Cake/Core/App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
```

**Comment by lGuillaume124** [comment]
becc41d300035d6dd1d7cdd7271a9bb2d1b2dd2c introduced a regression... I will fixed it as soon as possible.

**Comment by lGuillaume124** [comment]
It should be better now :)
