### ISSUE TITLE
Not working with nginx

### ISSUE THREAD

**Issue by RemiDesgrange** [Sonerezh/sonerezh#134]
Hi everyone,

I tried to set up sonerezh on my Debian 8+nginx. It failed so I tried from a fresh debian 8 with nginx 1.6.2 and php5-fpm (both from the debian  repo). 

I'm using your configuration from the doc.

The problem is : I don't have _any_ log. All pages are blank. But I can see the favicon (not so much info...) so i'm pointing out nginx in the right folder... What is the way for putting sonerezh in debug mode ?

**Comment by lGuillaume124** [comment]
Hello,

The demo instance (https://www.sonerezh.bzh/demo) runs on Nginx / Debian 8. So it works.
You can enable the debug mode by passing the CAKEPHP_DEBUG env variable to 1:

```nginx
[...]
    location ~ \.php {
        [...]
        fastcgi_param CAKEPHP_DEBUG 1;
    }
[...]
```

**Comment by RemiDesgrange** [comment]
Ok thanks, it's nginx I think or php fpm because it's not working and when I'm looking at the exchange between the server and the web browser via Wireshark the HTTP response body is empty. So I think I misconfigured nginx

**Comment by lGuillaume124** [comment]
Hi, did you fix your problem?

**Comment by RemiDesgrange** [comment]
I gave up 25 days ago. I just tried to put `phpinfo()` on top of the `index.php` file in `app/webroot`folder, and it didn't work. I don't have any error in the log this is (very) weird, because i have owncloud and other php app on this server. I will try this week-end to get to the bottom of this, but if I don't know how cakephp works (in term of logging). Maybe this is just me, do you have a dockerfile ?

**Comment by lGuillaume124** [comment]
You can find the Cake logs in app/tmp/logs/.
The Dockerfile is still under development and but available here : https://github.com/Sonerezh/docker

**Comment by RemiDesgrange** [comment]
I'll try this week-end, this is weird (but I already said that :-) )

**Comment by RemiDesgrange** [comment]
Ok this is now working, I apply the same config provide by the docker image, thanks for the help. 

Sonerezh could not connect to the database first, and I saw nothing in the log, just "Could not connect to database" in the UI, is that normal ?
