### ISSUE TITLE
Sonerezh can not read id3 tags when these tags were edited under Linux

### ISSUE THREAD

**Issue by sybiload** [Sonerezh/sonerezh#135]
Hi folks !

When id3 tags of any mp3 were edited under linux (for example with puddletag), these tags can not be read by Sonerezh.

I must edit them with mp3tag under windows so they can be read correctly.

Thanks in advance !

EDIT: Solved in 1.0.0-beta

**Comment by lGuillaume124** [comment]
Hi,
Could you send us one of your files please?

**Comment by sybiload** [comment]
Here is one mp3 that doesn't work correctly. It can't be played under Sonerezh but it works on a normal music player such as cmus.

https://goo.gl/eglZO9

**Comment by sybiload** [comment]
The issue seems to be solved when I updated to
