### ISSUE TITLE
First page has limited number of songs, until page 3

### ISSUE THREAD

**Issue by Porco-Rosso** [Sonerezh/sonerezh#136]
Hi, first of all thanks for the great project and continued work! 

I seem to be experiencing a bug, where the first page only displays 5 songs. When I click the second page it loads more, and then finally on the third page songs are loaded as I scroll down continuously.

At the moment I doubt this is intended functionality, but if it is could you share the reason why?

Merci pour le project!

<img width="854" alt="screen shot 2015-11-24 at 12 55 14 pm" src="https://cloud.githubusercontent.com/assets/7024527/11365993/a7a74948-92aa-11e5-84f7-941a701f5941.png">

**Comment by lGuillaume124** [comment]
You should not have to click on "2" or "next" to display the following page. It should be an automatic infinite scroll.

On which platform do you access to your Sonerezh instance please?

**Comment by Porco-Rosso** [comment]
I'm using chrome 46.0.2490.86 on OS X

**Comment by lGuillaume124** [comment]
Any errors from the server, or from your browser console?

**Comment by Porco-Rosso** [comment]
No messages on the console, but while checking I did notice: If I reduce the height of the browser window the automatic page loading works. 
I suspect it's an error regarding the css page height or min/max height. How does Sonerezh determine when to load more content?

**Comment by lGuillaume124** [comment]
The code is here: https://github.com/Sonerezh/sonerezh/blob/master/app/webroot/js/jquery.scroll.js

**Comment by atomiix** [comment]
Hi,

More than 1 year since this issue was opened. I guess I can close it.
