### ISSUE TITLE
Downloading install file /Téléchargement fichier install

### ISSUE THREAD

**Issue by philippebc** [Sonerezh/sonerezh#139]
Hi,

On 1.0.0-beta, during installation after filled all field and click to "Run!" button I download an "Install" file.
This problem seems affect a few persons but I don't find an understandable fix.

Thanks for your support,

Bonjour,

Sur la version 1.0.0-beta, durant l'installation, après avoir remplis tous les champs et cliqué sur le bouton "Run!", je télécharge un fichier "install".
Il semble que ce problème impacte déjà plusieurs personnes mais je ne suis pas arrivé à trouver une solution compréhensible.

Merci pour votre aide,

**Comment by nodiscc** [comment]
To efficiently address your problem you need to provide a few clues about your environment:

 * Web server name/version
 * PHP module name/version
 * Content of webserver or PHP error/access logs.

Content of the logfiles can help you find out what the problem is.

**Comment by philippebc** [comment]
PHP Version	5.6.15
System	Linux serveur.maven2-71.com 3.14.32-xxxx-grs-ipv6-64 #5 SMP Wed Sep 9 17:24:34 CEST 2015 x86_64
Build Date	Nov 9 2015 23:09:14
Configure Command	'./configure' '--enable-bcmath' '--enable-calendar' '--enable-exif' '--enable-ftp' '--enable-gd-native-ttf' '--enable-intl' '--enable-libxml' '--enable-mbstring' '--enable-opcache' '--enable-pdo=shared' '--enable-soap' '--enable-sockets' '--enable-wddx' '--enable-zip' '--prefix=/usr/local' '--with-apxs2=/usr/local/apache/bin/apxs' '--with-bz2' '--with-config-file-path=/usr/local/lib' '--with-config-file-scan-dir=/usr/local/lib/php.ini.d' '--with-curl=/opt/curlssl/' '--with-enchant=/usr' '--with-freetype-dir=/usr' '--with-gd' '--with-gettext' '--with-icu-dir=/usr' '--with-imap=/opt/php_with_imap_client/' '--with-imap-ssl=/usr' '--with-jpeg-dir=/usr' '--with-kerberos' '--with-libdir=lib64' '--with-libexpat-dir=/usr' '--with-libxml-dir=/opt/xml2' '--with-libxml-dir=/opt/xml2/' '--with-mcrypt=/opt/libmcrypt/' '--with-mm=/opt/mm/' '--with-mysql=/usr' '--with-mysql-sock=/var/lib/mysql/mysql.sock' '--with-mysqli=/usr/bin/mysql_config' '--with-openssl=/usr' '--with-openssl-dir=/usr' '--with-pcre-regex=/opt/pcre' '--with-pdo-mysql=shared' '--with-pdo-sqlite=shared' '--with-pic' '--with-png-dir=/usr' '--with-pspell' '--with-snmp' '--with-tidy=/opt/tidy/' '--with-xmlrpc' '--with-xpm-dir=/usr' '--with-xsl=/opt/xslt/' '--with-zlib' '--with-zlib-dir=/usr' 'LDFLAGS= '-L/usr/X11R6/lib64''
Server API	CGI/FastCGI
Virtual Directory Support	disabled
Configuration File (php.ini) Path	/usr/local/lib
Loaded Configuration File	/usr/local/lib/php.ini
Scan this dir for additional .ini files	/usr/local/lib/php.ini.d
Additional .ini files parsed	(none)
PHP API	20131106
PHP Extension	20131226
Zend Extension	220131226
Zend Extension Build	API220131226,NTS
PHP Extension Build	API20131226,NTS
Debug Build	no
Thread Safety	disabled
Zend Signal Handling	disabled
Zend Memory Manager	enabled
Zend Multibyte Support	provided by mbstring
IPv6 Support	enabled
DTrace Support	disabled
Registered PHP Streams	https, ftps, compress.zlib, compress.bzip2, php, file, glob, data, http, ftp, phar, zip
Registered Stream Socket Transports	tcp, udp, unix, udg, ssl, sslv3, sslv2, tls, tlsv1.0, tlsv1.1, tlsv1.2
Registered Stream Filters	zlib.*, bzip2.*, convert.iconv.*, mcrypt.*, mdecrypt.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk

**Comment by philippebc** [comment]
For your information, I tried with the 0.9 release version. I downloaded the "install" file again but the configuration file is available and the site runs.

**Comment by nodiscc** [comment]
Error logs?

**Comment by philippebc** [comment]
I'm not adevelopper, I don't find any error log. I can verify again but where?
Thanks

**Comment by nodiscc** [comment]
Default log location for apache logs on Debian-based distributions is `/var/log/apache2/*.log`

**Comment by philippebc** [comment]
I don't have access to this folder because my host is on a shared server (Mavenhosting).

**Comment by philippebc** [comment]
Could you provide MySQL script with administrator account and instruction for the config file in order to use and test the 1.0.0 Beta? Thanks

**Comment by lGuillaume124** [comment]
You can enable the debug toolbar if you add the following line in the ``.htaccess`` file:
```apache
SetEnv CAKEPHP_DEBUG 1
```
It may help you.

I attached the SQL file used to generate the database (MD5: bec243d1365dafbb84787b6ad3433904)
. But I can't provide an administrator account because its password hash depends on the salt key configured in your core.php file...

[sonerezh.sql.zip](https://github.com/Sonerezh/sonerezh/files/76625/sonerezh.sql.zip)

**Comment by philippebc** [comment]
Merci Guillaume.
I did it, but the debug toolbar didn't indicated any log "Il n'y avait pas d'entrées de log faîtes pour cette requête".

I will try to use it with the sql...

**Comment by philippebc** [comment]
Hello,

I have a fix!
In fact, the database architecture was created during the installation. So, I have modified the  **database.php.default** into the ./app/Config folder.
After filling the settings accordingly:
```php
public $default = array(
		'datasource' => 'Database/Mysql',
		'persistent' => false,
		'host' => 'localhost',
		'login' => 'user',
		'password' => 'password',
		'database' => 'database_name',
		'prefix' => '',
		//'encoding' => 'utf8',
```
The file is saved as **database.php** into the same folder.
After, the website seems to work!

======

Salut,

J'ai un correctif !
En fait, lors de l'installation l'architecture de la base de donnée est crée. Donc, j'ai modifié le fichier **database.php.default** dans le répertoire ./app/Config.
Après avoir compléter les réglages correctement : 
```php
public $default = array(
		'datasource' => 'Database/Mysql',
		'persistent' => false,
		'host' => 'localhost',
		'login' => 'user',
		'password' => 'password',
		'database' => 'database_name',
		'prefix' => '',
		//'encoding' => 'utf8',
```
Le fichier est sauvegarder en tant que **database.php** dans le même répertoire.
Après, lesite semble fonctionner !

**Comment by cjrobe** [comment]
Thanks philippebc, I had the same issue on shared hosting and the manual install worked great.
