### ISSUE TITLE
Mp3 files without Id3 tags all showns as "Unknown"

### ISSUE THREAD

**Issue by Tym17** [Sonerezh/sonerezh#142]
If music file have no Id3 tags, maybe display it in Unknown artist and Unknown album but at least change the title of the music by the title of the file ?

**Comment by lGuillaume124** [comment]
What is the interest of Sonerezh if your files do not have metadatas?

**Comment by Tym17** [comment]
This is a good point but however, on home made music there is not always metadatas.

**Comment by nodiscc** [comment]
A filename _is_ metadata (just not contained in tags). In the absence of tags, the logical thing to do would be displaying the filename as title.

**Comment by lGuillaume124** [comment]
Yes but Sonerezh needs more than just a filename as a title to run properly.

**Comment by Tym17** [comment]
Maybe it could bind the rest of the informations to unknown and set the file title as song title
