### ISSUE TITLE
Cannot choose output bitrate in conversion window

### ISSUE THREAD

**Issue by Raptor039** [Sonerezh/sonerezh#143]
Hi and thanks for your work on this wonderfull app !!

In the latest master branch, there is no possibility to choose the output bitrate in the conversion's window. The only choice is 256 kb/s. This bug is not present in the beta2 of Sonerezh.

---

Salut et merci pour votre travail, j'utilise Sonerezh au quotidien et je dois dire qu'il me fait oublier Deezer !! :dancer: 

Par contre, dans le dernier commit de la master branch, on ne peut plus choisir le bitrate de sortie lors d'une conversion d'un fichier. La barre à disparue ! Ce n'est pas le cas dans la beta2 qui fonctionne très bien.

Raptor.

**Comment by lGuillaume124** [comment]
The [demo instance](https://www.sonerezh.bzh/demo/settings) uses the latest commit on master and does not have this issue. And we did not change anything on the settings between the 1.0.0-beta and the 1.0.0-beta2 releases. Any errors / debug in your browser console?

**Comment by lGuillaume124** [comment]
Any news?

**Comment by Raptor039** [comment]
Toujours le même résultat avec la 1.1.1 installed from scratch et un clear du cache et des cookies du navigateur ( essayé sur firefox / chrome / edge / IE).

Je précise que mon serveur tourne sous Debian 7 avec Nginx et php5.4.

PS : désolé pour le temps de réponse

Voici une petite démo du problème en live (dsl pour la qualité j'ai capturé ça depuis le boulot en RDP sur mon PC à la maison) : https://youtu.be/gRnnblK31Eg

Even after a fresh install of Sonerezh from scratch, the problem is still there (clear cache & coockies from browser has no effect)

My server is on Debian 7 with Nginx and php5.4.

**Comment by lGuillaume124** [comment]
Indeed, I can reproduce this on my own instance.
