### ISSUE TITLE
Error Message: Invalid root path

### ISSUE THREAD

**Issue by Benedikt1992** [Sonerezh/sonerezh#144]
When I try to install sonerezh on a shared hosting server, i get the error message "Invalid root path" for the Music folder. Any Idea what is wrong? Please let me know if you need more informations.

**Comment by lGuillaume124** [comment]
This message is returned when the specified root path does not exist. Here is the test from [Model/Rootpath.php](https://github.com/Sonerezh/sonerezh/blob/master/app/Model/Rootpath.php):

```php
public $validate = array(
        'rootpath'	=> array(
            'pathExists'	=> array(
                'rule'			=> 'pathExists',
                'message'		=> 'Invalid root path'
            ),
            'isReadable'	=> array(
                'rule'			=> 'isReadable',
                'message'		=> 'Root path folder is not readable'
            ),
        )
    );

public function pathExists($options = array()) {
        if (!file_exists($this->data[$this->alias]['rootpath'])) {
            return false;
        }
        return true;
    }
```

Where ``$this->data[$this->alias]['rootpath']`` is the root path set on the settings page.

**Comment by nodiscc** [comment]
Changing the message to `Your configured root directory does not exist` might be nicer.

**Comment by lGuillaume124** [comment]
Hi nodiscc. Your suggestion will be integrated in the next release.

**Comment by lGuillaume124** [comment]
Merged.
