### ISSUE TITLE
Errror sonerezh & PHP7

### ISSUE THREAD

**Issue by PiXELART** [Sonerezh/sonerezh#147]
Hey guys, a little problem of compatibility between Sonerezh & PHP7 :

```FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot use 'string' as class name as it is reserved in /var/www/sonerezh/lib/Cake/Utility/String.php on line 24```

I'm using nginx 1.9.9 with PHP7-FPM 7.0.2-1~dotdeb+8.1

**Comment by lGuillaume124** [comment]
Yes, we've noticed that. Sonerezh works on CakePHP 2.6, which is not compatible with PHP7. We will upgrade CakePHP for the next major release (1.1.0).

**Comment by PiXELART** [comment]
Ok, j'ai hâte de voir ça alors! ;)

**Comment by lGuillaume124** [comment]
Please refer to #148
