### ISSUE TITLE
IndexedDB does not function in private browsing mode

### ISSUE THREAD

**Issue by ldleman** [Sonerezh/sonerezh#152]
Hello.

Thank for this application.
I tried but at startup i'm falling on : 

![2016-01-27 08_00_43-songs](https://cloud.githubusercontent.com/assets/2620979/12606318/ba6d9024-c4cc-11e5-93f5-a60f8213f408.png)

Any idea ?

**Comment by atomiix** [comment]
Hi !

I didn't found anything, but it seems to be firefox related.
Did you try to delete the Sonerezh IndexedDB and try again ?

**Comment by ldleman** [comment]
Hi ! 

I'v found the problem. 

It seem IndexedDB doesn't work on chrome and firefox when they are in
privacy mode (too bad for privacy but it works when you disables all
privacy options).

Others errors went when i test on WAMP in my windows environment but it
does not matter. 

Works like a charm on ubuntu, thanks for this beautiful app. 

is there a doc to create plugins ?

Le 2016-01-28 00:21, atomiix a écrit : 

> Hi ! 
> 
> I didn't found anything, but it seems to be firefox related.
> Did you try to delete the Sonerezh IndexedDB and try again ? 
> 
> --
> Reply to this email directly or view it on GitHub [1].

  

Links:
------
[1]
https://github.com/Sonerezh/sonerezh/issues/152#issuecomment-175908123

**Comment by atomiix** [comment]
You're right, it doesn't work in private mode, but only in Firefox for me.

There is no doc to create plugin except [the doc from CakePHP](http://book.cakephp.org/2.0/en/plugins/how-to-create-plugins.html)

**Comment by ldleman** [comment]
My chrome was opened in anonymous tab mode, maybe it's that ? 

Thx for the doc, i will read this :). 

Le 2016-01-28 09:36, atomiix a écrit : 

> You're right, it doesn't work in private mode, but only in Firefox for me. 
> 
> There is no doc to create plugin except the doc from CakePHP [1] 
> 
> --
> Reply to this email directly or view it on GitHub [2].

  

Links:
------
[1] http://book.cakephp.org/2.0/en/plugins/how-to-create-plugins.html
[2]
https://github.com/Sonerezh/sonerezh/issues/152#issuecomment-176054752

**Comment by lGuillaume124** [comment]
Very interesting issue! I will add it to the doc.

By the way, when can I read the next "Bordel de l'info"? :p

**Comment by ldleman** [comment]
Uh ! Spotted ! :D j'avais pas fait vue que le projet était frenchi ! :D Merci pour ce joli soft :) 
J'ai acheté une maison en ruine je suis donc pas mal en mode BTP, d’où l’intérêt de trouver une bonne alternative open source a deezer pour rythmer les pauses de placo et autres, du coup pas beaucoup de temps pour un nouveau bordel de l'info ce mois-ci mais j'y travaille pour février et je ne manquerais pas de mentionner ce joli ptit proj :D

**Comment by lGuillaume124** [comment]
Cool, merci beaucoup :)

**Comment by lGuillaume124** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=781982

**Comment by lGuillaume124** [comment]
Note for me: improve the documentation before close this issue.
