### ISSUE TITLE
Fatal error on cakephp_upgrade branch

### ISSUE THREAD

**Issue by PixiBixi** [Sonerezh/sonerezh#155]
Hello team!

See the bug:

`2016/01/31 14:25:29 [error] 18166#18166: *10 FastCGI sent in stderr: "PHP message: PHP Fatal error:  'break' not in the 'loop' or 'switch' context in /var/www/sonerezh/app/Vendor/Getid3/getid3.lib.php on line 285" while reading response header from upstream, client: 87.231.xx.xx, server: .eu, request: "POST /import HTTP/1.1", upstream: "fastcgi://unix://run/php/php7.0-fpm.sock:", host: ".eu", referrer: "http://.eu/import`

To fix it, just remove the break from the line 285

**Comment by lGuillaume124** [comment]
Thanks for your report! The fix has been merged to the development branch.
