### ISSUE TITLE
Language typo in french locale

### ISSUE THREAD

**Issue by NumEricR** [Sonerezh/sonerezh#159]
Hi,
There is a tiny typo in french locale. See [this translation](https://github.com/Sonerezh/sonerezh/blob/master/app/Locale/fra/LC_MESSAGES/default.po#L429).

We should read "(...) Remplissez juste les information**_s_** ci-dessous (...)" instead of "(...) Remplissez juste les information ci-dessous (...)".

**Comment by lGuillaume124** [comment]
Thanks for your report!
