### ISSUE TITLE
CSRF on add user form 

### ISSUE THREAD

**Issue by sabreen14** [Sonerezh/sonerezh#161]
We were testing the application, we found that it is possible to apply CSRF  attack on the "new user" form 
since there is no control with an Anti-CSRF token. Therefore, this flaw allows an attacker to use social engineering by phishing email to an administrator, forging him to execute a malicious remote script that can create users automatically on behalf the administrator. 
You can verify this vulnerability by using CSRF Tester tool; this tool generates the script that can be used to implement CSRF attack. Then, by sending a “phishing email” to Sonerezh’s Administrator and modified the script generated by CSRF Tester to generate the automatic HTTP request to the attacker’s server for the CSRF script. The Sonerezh’s Administrator, authenticated on the web application, opened his email and clicked on the link of the “phishing email”. Then automatically the new user, created by the CSRF script, is added in the application without the Administrator could notice that.
You can patch the application by adding a php class that implements an Anti-CSRF base64-encoded token for the “Add user” transaction. It is an open source class downloaded from http://bkcore.com/blog/code/nocsrf-php-class.html. You can invoke this class on the main files of this transaction, sonerezh-master\app\View\Users\index.ctp and sonerezh-master\app\Controller\UsersController.php.
Checking the security controls according to the best practices such as OWASP can be helpful to avoid any kind of attack. Indeed, Sonerezh is using old version of cakePHP framework that is vulnerable to CSRF attack. Additionally, checking CVE website before using the framework is important because this website lists all the potential vulnerabilities in the framework.

**Comment by lGuillaume124** [comment]
Indeed, Sonerezh is using an old version of CakePHP but we are currently working on it (on the branch "cakephp_upgrade"). We will also implement the CakePHP CSRF protection ( see http://book.cakephp.org/2.0/en/core-libraries/components/security-component.html#csrf-protection) for the next release.

Thank you for your vigilance.
