### ISSUE TITLE
English translation: Password reset email grammar 

### ISSUE THREAD

**Issue by KimBrodowski** [Sonerezh/sonerezh#162]
Hello,
I'm currently translating the English version into German for an intial commit (If that is helpful. Please be so kind to give feedback on that matter. Otherwise I'll just use it myself). The following in the English version does not appear to be correct though in my humble opinion.

`#: View/Emails/html/send_token.ctp:10`
`Hi, you receive this email because you asked for reset your password on Sonerezh.`

I'm not a native speaker, but I'd suggest: 

`Hi, you receive this email because you've requested a password reset on Sonerezh.`

Offtopic: Amazing app so far. I'm glad if I can help. Saves me quite a few bucks for my Google Play Music subscription in the future hopefully.

Greetings

**Comment by nodiscc** [comment]
https://github.com/Sonerezh/sonerezh/pull/163
