### ISSUE TITLE
V1.0 not working

### ISSUE THREAD

**Issue by eregnier** [Sonerezh/sonerezh#165]
Hello,

I tried to install sonerezh, but with both git repository and zip install after a chmod 755 and chown www-data + symlink in my /var/www folder I got a 404 on sonerezh/install

**Comment by nodiscc** [comment]
Any luck with https://github.com/Sonerezh/sonerezh/issues/50, https://github.com/Sonerezh/sonerezh/issues/41, https://github.com/Sonerezh/sonerezh/issues/123 ?

**Comment by KimBrodowski** [comment]
Some more information on your setup would be helpful as well. I setup Sonerezh on Apache2.4 with PHP-FPM a few days ago just fine. 

In case you use nginx you'll need to edit your "vhost's" configuration as well. 

An example can be found here: https://www.sonerezh.bzh/docs/en/annexes.html

**Comment by atomiix** [comment]
Hi,

Since we released Sonerezh 1.1.3 and we've got no news from you, I close this issue. Feel free to reopen it if needed.

**Comment by eregnier** [comment]
Hello guys,
I tried your solution when you gave it to me bu I did not succeed with it. I may have not spent as many time as it required to be solved, So I don't really know if your answer is good and still valid.

However thank you for your support.
