### ISSUE TITLE
Extreemly slow with high song count

### ISSUE THREAD

**Issue by Mechazawa** [Sonerezh/sonerezh#169]
My installation has a very high song count. This makes it impossible to go to both the artist and album section. Trying to open these kills the installation for a large period of time. Search works fine.

![http://i.imgur.com/peb0VHQ.png](http://i.imgur.com/peb0VHQ.png)

**Comment by lGuillaume124** [comment]
Hi,
#156 could interest you ;)

**Comment by Mechazawa** [comment]
I suggest that further discussion should be moved to #156 from now on then. It would time out when clicking any of the tabs after clicking something like albums. So the site would be unusable for quite some time.
