### ISSUE TITLE
Whitespace character

### ISSUE THREAD

**Issue by arkeine** [Sonerezh/sonerezh#177]
Hi,

In the search box, the whitespace characters are not remove before searching (before and after the entered text). This cause song not found.

**Comment by lGuillaume124** [comment]
Hi,

There is not whitespace character in the search box. I do not understand :/

**Comment by atomiix** [comment]
I think he's talking about trailing space like when you copy and past an artist name and there's a final space for example. We have to "trim" the query string.

**Comment by lGuillaume124** [comment]
Indeed!

**Comment by arkeine** [comment]
Exactly, I was not clear, I mean "trim" the user input.
