### ISSUE TITLE
Problem with file rights at installation

### ISSUE THREAD

**Issue by MightyCreak** [Sonerezh/sonerezh#178]
Hi!

In the installation steps, you ask to change the files rights for this: `chmod -R 775 sonerezh/`

The problem with that is that if you installed your instance by cloning the git repository, you now have a huge list of modified files (see git diff output: [sonerezh_right_changes_diff.txt](https://github.com/Sonerezh/sonerezh/files/216186/sonerezh_right_changes_diff.txt))

I don't find "775" to be the right rights to apply on the whole directory (there is no need to allow execution of all the PHP files). I think the file rights should be good out of the box (i.e. nothing to change after `git clone`).

Cheers!

**Comment by lGuillaume124** [comment]
Indeed, my mistake. I fix as soon as possible. Thank you for your vigilance.
