### ISSUE TITLE
Tracks duplicated on import

### ISSUE THREAD

**Issue by arkeine** [Sonerezh/sonerezh#180]
Hi, 

On every importation, I get duplicated entries in data base. 

I take a look here [#122](https://github.com/Sonerezh/sonerezh/issues/122) and here [#129](https://github.com/Sonerezh/sonerezh/issues/129) but it's not exactly the same problem.

I never removed files, I just add new files and import them. The importation end successfully, but when I run this script on the data base, I can see multiple entries for the same song:

`SELECT track_number,title,album,COUNT(*) FROM sonerezh.songs G                                     ROUP BY     track_number,title,album HAVING COUNT(*) > 1;`

So, I remove these links manualy with another script. Is it only me who have this bug?

PS: The clean script:

`DELETE sonerezh.songs  FROM sonerezh.songs LEFT OUTER JOIN (    SELECT MIN(id) as id, track_number,title,album    FROM sonerezh.songs     GROUP BY track_number,title,album ) as KeepRows ON    sonerezh.songs.id = KeepRows.id WHERE    KeepRows.id IS NULL;
`

**Comment by MightyCreak** [comment]
I also have duplicated tracks in the same album although I verified I only have the file once in all of my library.

**Comment by lGuillaume124** [comment]
Hi,

What version of Sonerezh do you use?

**Comment by MightyCreak** [comment]
The latest one: v1.1.1

**Comment by lGuillaume124** [comment]
Could you send us one or more tracks please?

**Comment by MightyCreak** [comment]
I'll email it to you

**Comment by arkeine** [comment]
I'm also using the last version v1.1.1.

I will send to you a sample of song which are duplicated. I have not the time now, but I will check if I remarke the same correlation that @MightyCreak said.

**Comment by arkeine** [comment]
I try to reset my db and import again.

I have now 2477 songs and, as MightyCreak said, I got 24 duplicated tracks. The duplicated tracks aren't the same than before.

**Comment by MightyCreak** [comment]
Could it be possible flag this issue as Bug and in priority High? Because it quite is ;)

**Comment by MightyCreak** [comment]
Is the bug fixed? I haven't seen a fix for it in the development branch.

**Comment by lGuillaume124** [comment]
Hi,
Just fixed :)

**Comment by MightyCreak** [comment]
Yes! Thanks!

**Comment by MightyCreak** [comment]
Since this bug is fixed with commit 4f3e60eebdb0a70a8e0c723765f35ab30fe7e049, shouldn't it be closed?
