### ISSUE TITLE
Can not add new user.

### ISSUE THREAD

**Issue by izaclorimer** [Sonerezh/sonerezh#189]
This has now happened to me twice - in 1.0.0 and 1.1.1 - and the only workaround is to duplicate and edit the database. When I try to add a new user (I only have two beforehand), the dialog exits without a confirmation and without adding a new user. Is this happening to anyone else?

Edit: Also, what type of hashing does sonerezh use?

**Comment by ltGuillaume** [comment]
Do you have the email option enabled? I had to disable it and user creation did work afterwards.

**Comment by lGuillaume124** [comment]
> Edit: Also, what type of hashing does sonerezh use?

See https://github.com/Sonerezh/sonerezh/blob/master/app/Controller/AppController.php#L23 and https://github.com/Sonerezh/sonerezh/blob/master/app/Controller/AppController.php#L59

Sonerezh uses `bcrypt()`, introduced by CakePHP with the `BlowfishPasswordHasher()` function (http://book.cakephp.org/2.0/en/core-libraries/components/authentication.html#using-bcrypt-for-passwords)

**Comment by atomiix** [comment]
Any news ?

**Comment by izaclorimer** [comment]
Sorry forgot to close after it was solved.

**Comment by Linuxine** [comment]
Hi, I have just made a fresh install of Sonerezh 1.1.3, and I have the exact same issue, I am totally unable to add a user, the window "Create a user" closes with no error in the GUI, or in any logs I have found, and nothing is done, no user creation... What was the solution for this one ?
