### ISSUE TITLE
Error on import when people mess with dates

### ISSUE THREAD

**Issue by P-EB** [Sonerezh/sonerezh#196]
Hey,

I found a funny thing importing my music library, some artist put full date in year field.

That made this happen: "Error: SQLSTATE[22P02]: Invalid text representation: 7 ERREUR:  syntaxe en entrée invalide pour l'entier : « 2011-04-19 »"

I suggest in parseMetadata, you do something like

`$metadata['year'] = strptime(end($file_infos['comments']['year']), "%Y")['tm_year'] + 1900;`

In app/Lib/SongManager/SongManager.php

Cheers.

**Comment by lGuillaume124** [comment]
See also #192

**Comment by P-EB** [comment]
Syntax is "Closes: #196 #207" :)

Closing.
