### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by StefOfficiel** [Sonerezh/sonerezh#198]
Hi!

In `/settings` in French you have noted : 

> Emplacement de la librairie

So, in French `Library` is `Bibliothèque`. In English `Librairie` is `Bookstore`!

Many thanks for Sonerezh !

---

Hello !

Dans `/settings` il est noté : 

> Emplacement de la librairie

Il serait plus correct de traduire `Library` par `Bibliothèque`. `Librairie` se dit `Bookstore` en Anglais ;-)

Un putain de merci pour Sonerezh !

**Comment by lGuillaume124** [comment]
What about "_Emplacement de la collection_"?

**Comment by StefOfficiel** [comment]
Pour moi, "_Bibliothèque_" me parle plus que "_collection_" !
__________________

For me, "_Bibliothèque_" is more meaningful than "_collection_" !
