### ISSUE TITLE
Improve the warn message on the cli tool

### ISSUE THREAD

**Issue by tititototutu** [Sonerezh/sonerezh#199]
Bonjour,

J'ai lancé une importation depuis la ligne de commande pour peupler ma base de donnée et celle ci a planté en cours avec le message suivant:

```
$./Console/cake sonerezh import -vr ../Loop/
.....
2016-06-07 16:23:34 Warning: pcntl_signal_dispatch() has been disabled for security reasons in [/srv/www/zik/app/Console/Command/SonerezhShell.php, line 115]
PHP Fatal error:  'break' not in the 'loop' or 'switch' context in /srv/www/zik/app/Vendor/Getid3/module.audio-video.asf.php on line 79
Fatal Error Error: 'break' not in the 'loop' or 'switch' context in [/srv/www/zik/app/Vendor/Getid3/module.audio-video.asf.php, line 79]

2016-06-07 16:23:34 Error: 'break' not in the 'loop' or 'switch' context in [/srv/www/zik/app/Vendor/Getid3/module.audio-video.asf.php, line 79]
.....
```

Depuis je ne peux plus relancer l'importation.

```
$./Console/cake sonerezh import -vr ../Loop/

Welcome to CakePHP v2.8.1 Console
---------------------------------------------------------------
App : app
Path: /srv/www/zik/app/
---------------------------------------------------------------
[WARN] The import process is already running via another client or the CLI
```

Y a t'il un fichier de lock quelque part? C'est une installe neuve en version 1.1.1.

Merci d'avance.

Désolé d'avoir redigé en francais mais mon anglais est lamentable (pire que mon breton ;)

Kenavo!

**Comment by tititototutu** [comment]
ok, il m'a suffit de supprimer la dernière entrée dans ma base de donnée sur la table songs.

Manque plus qu'a savoir pourquoi cette chanson fait planter l'importation.

**Comment by lGuillaume124** [comment]
Bonjour @tititototutu 
En effet il y a un verrou. Il est possible de réinitialiser le système de verrou en utilisant le bouton "Nettoyer le cache", depuis la page des paramètres. On devrait améliorer le message d'erreur et l'indiquer.

--
We should improve the warning message and explain how to reset the lock file if needed (just by clicking on the button "Clear cache", from the settings page).
