### ISSUE TITLE
Roadmap down

### ISSUE THREAD

**Issue by peterbrinck** [Sonerezh/sonerezh#202]
Hi!

Just wanted to check the roadmap, but it's down. Giving the default NGINX page

**Comment by lGuillaume124** [comment]
Hi,
Indeed, I rebooted our server 4 days ago and I did not restart Docker... Sorry for the inconvenience.

**Comment by rototom** [comment]
and down again...

**Comment by Tulpenzwiebel** [comment]
Hi!
It's down again. It's an 504 Gateway Time-out error

**Comment by goegol** [comment]
and done again...
