### ISSUE TITLE
Is Sonerezh compatible with php7.0?

### ISSUE THREAD

**Issue by Flaburgan** [Sonerezh/sonerezh#204]
Hi, I found nowhere in the doc the max php version supported, and the browser compatibility.
I'm trying to install sonerezh on a kimsufi with Ubuntu 16.04 which comes with php7.0, nginx 1.10 and postgresql 9.5.

I installed all the requirements, adapted the nginx conf example to work with php 7, and now I have nothing else than a white screen. No error in nginx logs. I never ran a php app on a dedicated server before, so not sure if there is something else I should do with fastcgi or fpm...

Thanks in advance.

**Comment by ltGuillaume** [comment]
Yes, I'm running nginx 1.10.1 and 7.0.7 with Sonerezh. This is my nginx server block:
```
    server {
            listen 80;
            server_name ***;

            root /srv/http/sonerezh/app/webroot;

            location / {
                    alias /srv/http/sonerezh/app/webroot/;
                    fastcgi_param PHP_VALUE open_basedir="/srv/http/sonerezh/:/mnt/hdd/music/";
                    try_files $uri $uri/ /index.php?$args;
                    expires 14d;
                    add_header Cache-Control 'public';
            }

            location ~ \.php$ {
                    alias /srv/http/sonerezh/app/webroot/$1;
                    include fastcgi_params;
#                   fastcgi_param CAKEPHP_DEBUG 1;
                    fastcgi_split_path_info ^(.+\.php)(/.+)$;
                    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                    fastcgi_param PATH_INFO $fastcgi_path_info;
                    fastcgi_param modHeadersAvailable true; #Avoid sending the security headers twice
                    fastcgi_pass unix:/run/php-fpm/php-fpm.sock;
                    try_files $uri =404;
            }
```

**Comment by diyfr** [comment]
I was forced to change the timeout because I had an error imports

`Maximum execution time of 30 seconds exceeded in .../app/Vendor/Getid3/module.tag.id3v2.php, line `286]`

**Comment by ltGuillaume** [comment]
@diyfr 
So I'm guessing you set `fastcgi_read_timeout 180;` or something?

**Comment by diyfr** [comment]
Yes
Or in .htaccess
php_value max_execution_time 60
Or php
ini_set('max_execution_time',60); 
is the bulk import after you empty the base.
60 seconds is correct and it's work

**Comment by Flaburgan** [comment]
Is there an IRC channel or any form of chat support? I need help to debug my installation.

And about this issue, what about an indication somewhere to the version supported?

**Comment by Flaburgan** [comment]
I'm sorry to ask for support on Github but I still don't success to install sonerezh. My nginx config looks ok, I just have a totally empty white page on http://zik.geexxx.fr/install. Nothing in the error log of nginx, a classic access in the access log. Nothing in `/var/log/php7.0-fpm.log` too. Can anyone indicate me where the logs are?

**Comment by Flaburgan** [comment]
Oh and I have `app/webroot/index.php.save` which is created when I go to `/install` so I suspect something is happening, I just don't now what.

**Comment by iziwas** [comment]
I think if you put the debug mode in sonerezh, Cakephp should display some messages.
To put sonerezh in debug mode, apparently you need to create a var with this function.
 `putenv('CAKEPHP_DEBUG'); `

When it's okay for you, just destroy this variable.

**Comment by Flaburgan** [comment]
In which file should I add it?

**Comment by iziwas** [comment]
app/Config/core.php for example, line 33 just before the "if"

**Comment by Flaburgan** [comment]
No output with those modifications:
```
putenv('CAKEPHP_DEBUG');
    /*if (getenv('CAKEPHP_DEBUG')) {*/
        Configure::write('debug', 2);
    /*} else {
        Configure::write('debug', 0);
    }*/

**Comment by iziwas** [comment]
Just you need to keep the "if/else". don't comment it.
If you comment this block, you will see nothing

**Comment by Flaburgan** [comment]
I tried without commeting it first ;)

**Comment by Flaburgan** [comment]
I'm sorry I'm really a noob with PHP, there isn't anything to restart right? A cache or anything.

**Comment by iziwas** [comment]
normally no restart

**Comment by ltGuillaume** [comment]
@Flaburgan 
> My nginx config looks ok 
Then post it here, so we can have a look :)

**Comment by Flaburgan** [comment]
```
server {
    listen      80;
    server_name zik.geexxx.fr;
    root        /var/www/sonerezh/app/webroot;

    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$args;
        expires 14d;
        add_header Cache-Control 'public';
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_index index.php;
        fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
        include /etc/nginx/fastcgi_params;
        fastcgi_param CAKEPHP_DEBUG 1;
    }
}
```
Written based on [the official source](https://www.sonerezh.bzh/docs/en/annexes.html). Is there something equivalent to `mod_rewrite` I have to activate on Nginx?

**Comment by ltGuillaume** [comment]
Try to add the "alias" line as I did in the example I posted above.

**Comment by Flaburgan** [comment]
So with this config:
```
server {
    listen      80;
    server_name zik.geexxx.fr;
    root        /var/www/sonerezh/app/webroot;

    #index index.php;

    location / {
        alias /var/www/sonerezh/app/webroot/;
        fastcgi_param PHP_VALUE open_basedir="/var/www/sonerezh/:/home/sonerezh/music";
        try_files $uri $uri/ /index.php?$args;
        expires 14d;
        add_header Cache-Control 'public';
    }

    location ~ \.php$ {
        alias /var/www/sonerezh/app/webroot/$1;
        include fastcgi_params;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param modHeadersAvailable true; #Avoid sending the security headers twice
        try_files $uri =404;
        #fastcgi_index index.php;
        fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
        #include /etc/nginx/fastcgi_params;
        fastcgi_param CAKEPHP_DEBUG 1;
    }
}
```
I finally have the install page displaying! I also had to install `php7.0-pgsql` to finish the install, the guide can probably be updated to mention that. I now just logged in and got this error:

```
The request has been black-holed

Error: The requested address '/login' was not found on this server.
Stack Trace

    CORE/Cake/Controller/Component/SecurityComponent.php line 240 → SecurityComponent->blackHole(UsersController, string)
    CORE/Cake/Utility/ObjectCollection.php line 128 → SecurityComponent->startup(UsersController)
    CORE/Cake/Event/CakeEventManager.php line 243 → ObjectCollection->trigger(string)
    CORE/Cake/Controller/Controller.php line 678 → CakeEventManager->dispatch(CakeEvent)
    CORE/Cake/Routing/Dispatcher.php line 189 → Controller->startupProcess()
    CORE/Cake/Routing/Dispatcher.php line 167 → Dispatcher->_invoke(UsersController, CakeRequest)
    APP/webroot/index.php line 107 → Dispatcher->dispatch(CakeRequest, CakeResponse)
```

Note that the index (zik.geexxx.fr) is returning a 403, so I still have something messed up.

**Comment by iziwas** [comment]
Just to know, do you have the **mod_rewrite** activated on nginx ?

**Comment by Flaburgan** [comment]
There is no such thing that "mod_rewrite" in nginx, though I uncommented `index index.php` line in nginx (I have commented it previously to match exacty @ltGuillaume config file) and the error is now gone ;)

Thanks everyone!

**Comment by ltGuillaume** [comment]
So it's all working now? Great! :D

**Comment by iziwas** [comment]
I can access on his login page on zik.geexxx.fr so i think it works ^^.
Issue closed =). Well done guys !

**Comment by Flaburgan** [comment]
It looks like it works, though I don't success to create another user. No error in the interface nor in nginx or php-fpm logs... Btw is the 1.2 version coming soon?
