### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by MightyCreak** [Sonerezh/sonerezh#209]
Sorry to pop the question, but there's been no dev in the past two months.

I need to know if you're still behind this project or not, because there's a lot of work left to do and even the interesting PRs, like pre-buffering of the next song #114, haven't been touched although it's here for almost an entire year.

So, is the project dead?

**Comment by atomiix** [comment]
Hi,

The project is not dead but we didn't have time to work on it last few weeks.
My bad about the pre-buffering PR, I answered to someone about this but not directly on the PR feed.
I'll add a reference to it ;)

So, the project is not dead

**Comment by MightyCreak** [comment]
Good to know, thanks ;)
