### ISSUE TITLE
Centos 7 - The request has been black-holed

### ISSUE THREAD

**Issue by kiwiASRALL** [Sonerezh/sonerezh#211]
Salut,

sonerezh a été testé sur Centos 7 ?

J'ai un problème à l'installation. 

centos 7 + nginx + mariadb
récupération du repo git, compilation de avconv. 

Premier soucis, sur la page d'install:

>  libav-tools (avconv) n'est pas installé. Sonerezh ne pourra pas convertir vos musiques. 

alors que
```
# whereis avconv
avconv: /usr/local/bin/avconv
```
Peu importe pour le moment. 
Je remplis les champs, clique sur 'Run' et j'obtiens:

> 
> The request has been black-holed
> 
> Error: The requested address '/install' was not found on this server.

Page title: Errors et le lien reste sur /install

Logs cakephp:

> Request URL: /api/heartbeat
> Stack Trace:
> #0 /srv/www/sonerezh/lib/Cake/Controller/Component/SecurityComponent.php(240): SecurityComponent->blackHole(Object(ApiController), 'auth')
> #1 [internal function]: SecurityComponent->startup(Object(ApiController))
> #2 /srv/www/sonerezh/lib/Cake/Utility/ObjectCollection.php(128): call_user_func_array(Array, Array)
> #3 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
> #4 /srv/www/sonerezh/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
> #5 /srv/www/sonerezh/lib/Cake/Controller/Controller.php(678): CakeEventManager->dispatch(Object(CakeEvent))
> #6 /srv/www/sonerezh/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
> #7 /srv/www/sonerezh/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ApiController), Object(CakeRequest))
> #8 /srv/www/sonerezh/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
> #9 {main}
> 2016-07-19 22:46:00 Error: [BadRequestException] The request has been black-holed
> Request URL: /api/heartbeat
> Stack Trace:
> #0 /srv/www/sonerezh/lib/Cake/Controller/Component/SecurityComponent.php(240): SecurityComponent->blackHole(Object(ApiController), 'auth')
> #1 [internal function]: SecurityComponent->startup(Object(ApiController))
> #2 /srv/www/sonerezh/lib/Cake/Utility/ObjectCollection.php(128): call_user_func_array(Array, Array)
> #3 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
> #4 /srv/www/sonerezh/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
> #5 /srv/www/sonerezh/lib/Cake/Controller/Controller.php(678): CakeEventManager->dispatch(Object(CakeEvent))
> #6 /srv/www/sonerezh/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
> #7 /srv/www/sonerezh/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ApiController), Object(CakeRequest))
> #8 /srv/www/sonerezh/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
> #9 {main}

j'ai tenté de vider le app/tmp/cache. Sans succès.

La conf nginx est celle de votre doc. Quelles informations supplémentaires avez-vous besoin ?

Avez-vous une idée ?

Merci l'équipe!

**Comment by kiwiASRALL** [comment]
Ok j'ai trouvé pour le gros problème de "black hole":
`fastcgi_param CAKEPHP_DEBUG 2;`
dans la conf nginx

Sur /install:
`Warning (2): session_start(): open(/var/lib/php/session/sess_linlrsevo9l261edjbehs2k6d1, O_RDWR) failed: Permission denied (13) [CORE/Cake/Model/Datasource/CakeSession.php, line 708]`

résolu par:
chown sonerezh: /var/lib/php/session

Je ne sais pas si c'est la solution la plus propre ?

Sinon même si à l'installation il me dit qu'il ne trouve pas 'avconv', le code fait un $ where avconv || ffmpeg ou quelque chose comme ça, l'applicatif sera en mesure de l'utiliser tout de même ?

**Comment by MightyCreak** [comment]
You can easily test by putting a flac file on your disk and see if the file plays (you need to wait a little for the conversion to be done, like 1 minute max).

I'm using this feature everyday on a Debian which, I think, also have avconv... Well, at home I have a Fedora and it works too.

**Comment by kiwiASRALL** [comment]
Yeah, good idea. It was not working however. 

To resolved this issue, in pool config of phpfpm:

> /etc/php-fpm.d/www.conf
- ;env[PATH] = /usr/local/bin:/usr/bin:/bin
+ env[PATH] = /usr/local/bin:/usr/bin:/bin

I simply uncomment env path to have /usr/local/bin where I have avconv. 

Now, all works. 
Thank you.
