### ISSUE TITLE
Sort albums by band instead of album

### ISSUE THREAD

**Issue by MightyCreak** [Sonerezh/sonerezh#223]
IMO we remember the bands names more than their albums, so first we find for the band, then for one of their albums. This is also how Deezer sorts the user's "albums" page.

I made a test end I find it way more useful than sorting by album:
https://github.com/MightyCreak/sonerezh/commit/88d89752d43ae75f33b3b7afabaed59332e4ba7c

If one reads this, I encourage him to edit his files locally and try it, it's really better.

Even better would be to have the choice, but the changes would be way more intrusive.

**Comment by MightyCreak** [comment]
Around the same line you can also increase the amount of albums in the first page (I personally increased it to 60):

    -                     'limit' => 36
    +                     'limit' => 60

And also you can remove the latest albums line:

    -             if ($page == 1) {
    -                 $latests = $this->Song->find('all', array(
    -                     'fields' => array('Song.id', 'Song.band', 'Song.album', 'Song.cover'),
    -                     'conditions' => $subQuery,
    -                     'order' => 'Song.created DESC',
    -                     'limit' => 6
    -                 ));
    -             }

**Comment by ltGuillaume** [comment]
Nice catch. I think you need to change the same thing on line 166 and line 196 to support all databases. Furthermore, it's even nicer to use `'order' => ['Song.band', 'Song.album'],`, so that it's sorted by artist name first, then by album name.

**Comment by MightyCreak** [comment]
Thanks! I'll do that! ;)

Any news on the next release?

**Comment by ltGuillaume** [comment]
Looks like you were asking me, but although I sort of have the same username as @lGuillaume124, I'm not him ;) So no idea when there's gonna be an update :P

**Comment by MightyCreak** [comment]
Indeed, I got confused, sorry ;)

**Comment by lGuillaume124** [comment]
I propose to add two labels to sort the page "by album", or "by band name".

**Comment by MightyCreak** [comment]
What's the default sort? (I'd vote for album).
Is the choice saved in the users preferences?

**Comment by lGuillaume124** [comment]
I can store your choice in the cookie.

**Comment by MightyCreak** [comment]
In the user's preferences would be better, for instance I'm using Sonerezh both at home and at work, or even at a friend's. (Personally, if album sort is the choice by default, I don't really care, but other users might not like the sort by album by default ;)).

**Comment by lGuillaume124** [comment]
Hi,

Commit https://github.com/Sonerezh/sonerezh/commit/1feb86882f10919fe53c4e4e7747ab585cb5a350 introduces a new column in the users' table named ``preferences`` which, as you can guess, will be used to store the users preferences.

For the moment, we just have the sort preference on the albums page but we will be able to easily add more options in this column as long as they are json formatted :)
As the preferences are part of the users table, they are automatically loaded by CakePHP in the session's data by the ``Auth`` component when the user signs in. So I forgot the cookie and it's clearly easier and more flexible in this way.

Thanks a lot for your suggestions!

By the way the next release will be 1.2.0 (not 1.1.2) because I modified the database schema ;)

**Comment by MightyCreak** [comment]
Once we have the options to sort "by artists" or "by album", I think we can remove entirely the "Artists" page since it will be redundant. And if we want to go even further, I think we can even make the "Albums" page the main page.

This way I'd have "Albums" and "Playlist".

I would even remove the "Recently added" in the album page (that's what I did on my instance actually) and create an "Activity" page to list this kind of info.
