### ISSUE TITLE
Sonerezh  on a subdomain doesn't work?

### ISSUE THREAD

**Issue by genma** [Sonerezh/sonerezh#228]
Actually I use the last Sonerezh version and it works great. I've create a subdomain, configure nginx as in order to make music.mydomain.org go to Sonerezh but it doesn't work.  On a a sublevel as mydomain.org/Sonerezh it works great.

Any idea? It seems some apps can't work on a subdomains, only on a sublevel.

**Comment by lGuillaume124** [comment]
Hi,

Any errors in your Nginx logs? I use my own personnal instance on a sonerezh.bzh subdomain. Here is my server-block:

```nginx
server { # -- Private Sonerezh

    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name subdomain.sonerezh.bzh;
    root /root_folder;

    # SSL Configuration
    [...]

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    # Serve static images from resized folder
    location ~* \/([^\/]+_[0-9]+x[0-9]+\.[a-z]+) {
        try_files /img/resized/$1 /index.php?$args;
        expires 7d;
    }

    location ~ \.php {
        try_files $uri =404;
        fastcgi_pass php5-fpm-sonerezh-sock;
        fastcgi_index index.php;
        include fastcgi.conf;
        fastcgi_param CAKEPHP_DEBUG 1;
    }

    access_log /log_folder;
    error_log /log_folder;

}
```

**Comment by genma** [comment]
Thanks for the answer. I'm using Son on a Yunohost instance. I've tried to reinstall it on a virtual machine and I've a message "Currently Sonerezh can only be installed on a subpath domain".
I'll check in Yunohost app installation script why I've this message.

I'll check if I can install it manually on a subdomain, with your explainations / configuration files samples. 
Thanks for that. After, I'll try to modify the "yunohost Sonerezh  package" in order to allow it to be installed on a subdomain :)

If you want, you can close this issue.

**Comment by TomMilon** [comment]
Hello :)

@genma did you managed to use subdomain for your Sonerezh app at last? 

I choose a subdomain for my sonerezh implementation and this is what happen :
1- _sonerezh.mydomain.org_ redirect me on _mydomain.org/yunohost/sso/_ (I couldn't find this redirection in this nginx conf)
2- _sonerezh.mydomain.org/sonerezh/_ works (but i'd like to have _sonerezh.mydomain.org_ working)

I've worked on nginx conf but nothing conclusive. Have you any idea?
NB : The DNS _sonerezh.mydomain.org_ is configured on the same IP as _mydomain.org_
