### ISSUE TITLE
[Bug] End space in directory name

### ISSUE THREAD

**Issue by Knah-Tsaeb** [Sonerezh/sonerezh#23]
If any directory in root music folder have additional space at end of name, Sonerezh generate error (PHP Fatal error:  Allowed memory size of 763363328 bytes exhausted).

I not try if directory begin by space reproduce the bug.

**Comment by lGuillaume124** [comment]
Hi,

What is your PHP version please?

**Comment by Knah-Tsaeb** [comment]
I use PHP 5.6.6 under Archlinux.
