### ISSUE TITLE
no sound...

### ISSUE THREAD

**Issue by benoitldr** [Sonerezh/sonerezh#230]
Hello,

Sonerezh seems to be a great apps, the installation via docker is OK but when I try to play some music the time runs but no sound ???

Any idea ?

Greetings

**Comment by nodiscc** [comment]
Hi @benoitldr 

 * Do you have any error messages/warnings in your browser console or server logs?
 * What browser?
 * What is the format of the audio files?
 * Is the sound level turned up and are you able to play those files on another player?

**Comment by atomiix** [comment]
Hi @benoitldr,

As there is no news from you since a while, I close this Issue. Feel free to reopen it if needed.
