### ISSUE TITLE
Database error on invalid metadata

### ISSUE THREAD

**Issue by oschettler** [Sonerezh/sonerezh#232]
With one of my MP3 files, on import, the Song->save() call raises an exception with "SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '??0' for column 'year' at row 1".

This happens in PHP 7.0

**Comment by atomiix** [comment]
Hi,

Can you send us your mp3 file before we merge your PR ?

**Comment by oschettler** [comment]
This is a bit embarrassing but no, I can't find the offending file.

**Comment by lGuillaume124** [comment]
Hi @oschettler,

The release 1.1.3 should fix your problem.
