### ISSUE TITLE
No thumbnails with MP3 files

### ISSUE THREAD

**Issue by dlazzy** [Sonerezh/sonerezh#234]
Hello,

I've just installed Sonerezh and imported my songs, but there is a problem.
I don't have thumbnails for my song. I have a broken image.
Sonerezh don't find my thumbnail. The URL is :  
img/thumbnails/3d54739406dc364cd15a7c39d27c08f2_65x65.jpeg
And got a 404 not found (NGINX)

If I remove the size argument : 
img/thumbnails/3d54739406dc364cd15a7c39d27c08f2.jpeg the image is found.

How to fix that ?

**Comment by atomiix** [comment]
Hi,

Can you check if you have php-gd enabled ?
If so, it may be because of your nginx configuration.

keep me in touch.

**Comment by dlazzy** [comment]
Hello,

I've installed php-gd, restarted ngix and no thumbnails anyaway.
Can you explain how to enable php-gd for my nginx configuration thank your very much

**Comment by atomiix** [comment]
If you use php-fpm you have to restart it too. 

Can you check with a phpinfo if gd is really enabled
<img width="942" alt="capture d ecran 2016-12-17 a 21 17 07" src="https://cloud.githubusercontent.com/assets/2168836/21289441/4be22ffc-c49e-11e6-99d6-2657cfcd5713.png">

There is no need to change the nginx configuration if the problem comes from php-gd

**Comment by dlazzy** [comment]
I have php-gd enabled with version 2.1.1 (checked with phpinfo), restarted php7.0-fpm but no thumbnails.

**Comment by atomiix** [comment]
Well, is your nginx server block like the one in our [doc](https://www.sonerezh.bzh/docs/en/annexes.html#nginx-server-block-example) ?
If so, the last thing to do is to look at your log files to find where the problem comes from.

**Comment by dlazzy** [comment]
My log show this about Sonerezh : 
`2016/12/17 00:41:52 [error] 1409#1409: *16 open() "/var/www/music/sonerezh/app/webroot/img/thumbnails/07cea82b09f413cc430e3b0ccc67dd99_65x65.jpeg" failed (2: No such file or directory), client: 88.219.184.52, server: myserver, request: "GET /img/thumbnails/07cea82b09f413cc430e3b0ccc67dd99_65x65.jpeg HTTP/2.0", host: "myserver", referrer: "myserver"
`So not found.

I will give you my nginx block : (sonerezh run as a subdomain)
```
server {
    listen 80;
    listen [::]:80;
    server_name mysubdomain;
    return 301 https://$host$request_uri;
    location /.well-known/acme-challenge/ {
        alias /var/run/acme/acme-challenge/;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name mysubdomain;

    index index.php index.html index.htm;
    root /var/www/music/sonerezh/app/webroot;

    location / {
        try_files $uri $uri/ /index.php?$args;
#        expires 14d;
#        add_header Cache-Control 'public';
    }

    location ~* \.php$ {
        try_files $uri =404;
        include /etc/nginx/fastcgi_params;
        fastcgi_pass unix:/run/php/php7.0-fpm.sock;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_read_timeout 600s;
    }

    location ~* \.(?:html|css|jpg|jpeg|png|gif|ico|js|woff|eot|svg|ttf)$ {
        expires 1M;
        add_header Cache-Control "public";
    }

    location /.well-known/acme-challenge/ {
        alias /var/run/acme/acme-challenge/;
    }

    include /etc/nginx/ssl.conf;
    ssl_certificate_key /var/lib/acme/live/mysubdomain/privkey;
    ssl_certificate /var/lib/acme/live/mysubdomain/fullchain;
}
```

I really don't know what's wrong with my block :/ Thanks for your help :)

**Comment by atomiix** [comment]
Can you try without these 2 lines : 
`fastcgi_split_path_info ^(.+\.php)(/.+)$;`
`fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;`

**Comment by dlazzy** [comment]
By remove these lines I can't access to sonerezh, my login page is not here !
I will put it again.

Don't loose your time with this problem. Maybe I will make a reinstall ! Thanks !
