### ISSUE TITLE
Pas de lecture des morceaux - résolu

### ISSUE THREAD

**Issue by samguili** [Sonerezh/sonerezh#235]
Après installation et import des musiques, aucune piste ne se lançait.
Il s'avère que ce problème était dû au mode de navigation privée activé sur firefox. Pour que la lecture fonctionne, il faut absolument ajouter une exception pour accepter les cookies du domaine dans le paramétrage de l'historique de firefox.

**Comment by nodiscc** [comment]
Shouldn't this be added to the documentation?

**Comment by lGuillaume124** [comment]
I just added a new section: https://www.sonerezh.bzh/docs/en/annexes.html
