### ISSUE TITLE
install -> 404 Not Found

### ISSUE THREAD

**Issue by Ryogo-Z** [Sonerezh/sonerezh#237]
Trying to install Sonerezh to a subdirectory on my nginx web-server.
Tried to use config (adapted) from https://www.sonerezh.bzh/docs/en/annexes.html with no success.

**Comment by Ryogo-Z** [comment]
OK, I've managed to install and everything's fine.

**Comment by ekianjo** [comment]
@Ryogo-Z I am experiencing the same issues, mind sharing your config?

**Comment by Ryogo-Z** [comment]
Sure, why not.

`# NGinX generated config file
user    www;
worker_processes        2;
worker_cpu_affinity     0101;
master_process  off;
worker_priority 10;
# access_log /var/log/nginx/access.log;
error_log       /var/log/nginx/error.log;
pid     /var/run/nginx.pid;
worker_rlimit_nofile    8192;

events {
        worker_connections      512;
}

http {
        include /usr/local/etc/nginx/mime.types;
        include /usr/local/etc/nginx/fastcgi_params;
        default_type    application/octet-stream;
        log_format   main '$remote_addr - $remote_user [$time_local]  $status '
        '"$request" $body_bytes_sent "$http_referer" '
        '"$http_user_agent" "$http_x_forwarded_for"';
        sendfile        on;
        client_max_body_size    16M;

        server {
                listen  80;
                server_name     XXX;
                access_log      /var/log/nginx/access.log       main;
                index index.php;

                gzip            on;
                gzip_types      text/plain text/css application/x-javascript text/xml application/xml application/xml+rss text/javascript application/json;
                gzip_comp_level  9;

                root    /usr/home/www/;

                location ^~ /music/ {
                        auth_basic off;
                        alias /usr/home/www/music/app/webroot/;
                        index index.php;
                        try_files $uri $uri/ /music//music/index.php?$args;

                        location ~ ^(?<script_name>.+?\.php)(?<path_info>/.*)?$ {
                                alias /usr/home/www/;

                                try_files       $script_name = 404;
                                include /usr/local/etc/nginx/fastcgi_params;
                                fastcgi_index index.php;
                                # fastcgi_param PATH_INFO $path_info;
                                # fastcgi_param SCRIPT_FILENAME $request_filename;
                                fastcgi_pass unix:/var/run/php-fpm.sock;
                        }
                }
        }
}`
