### ISSUE TITLE
suggestion multi utilisateurs.

### ISSUE THREAD

**Issue by Magicalex** [Sonerezh/sonerezh#24]
Bonjour,

Déjà pour une beta je trouve l'outil bien réussi.

Mais... je trouve que le système multi utilisateurs n'en n'est pas vraiment un. Au sens ou c'est plus un partage d'une bibliothèque. Je pense qu'il serait plus intéressant que chaque utilisateur puisse avoir a propre bibliothèque. Et que à partir de cette bibliothèque que l'on puisse avoir éventuellement des possibilités de partage avec d'autre utilisateur. (partage de playlist, voir de bibliothèque entière comme maintenant)

Après ça demande de revoir deux trois choses notamment au niveau de la bdd, donc c'est un choix à faire.

**Comment by nodiscc** [comment]
The current system fits me well. Just install multiple sonerezh instances if you need multiple music libraries.

**Comment by lGuillaume124** [comment]
Salut,

Nous y avons pensé lors du développement, mais nous avons abandonné l'idée parce qu'elle ne correspond pas à la philosophie du projet : le partage. Seules les playlists restent propres à chaque utilisateur.

Dans le futur on travaillera à un système de partage de pistes / albums / artistes.
