### ISSUE TITLE
Install script doesn't create the database

### ISSUE THREAD

**Issue by MightyCreak** [Sonerezh/sonerezh#241]
Hi!

I just made a fresh install and I'm following the [Install on a dedicated server](https://www.sonerezh.bzh/docs/en/installation.html#installation-on-a-dedicated-server) doc.

It never says that you have to create the Sonerezh database manually, so you have to go in the [Installation example on Ubuntu Server](https://www.sonerezh.bzh/docs/en/installation.html#installation-example-on-ubuntu-server) to get the commands to type in.

Two solutions to that:
1. Add the text that says you have to create the database manually
2. The installation script handles that by itself

I personally prefer solution 2 ;)

**Comment by lGuillaume124** [comment]
Hi,

Apparently we don't read the same doc :)

![selection_039](https://cloud.githubusercontent.com/assets/3330841/21304984/28db9df0-c5c9-11e6-9326-794721eb15f8.png)

https://www.sonerezh.bzh/docs/en/installation.html#create-the-database

**Comment by MightyCreak** [comment]
Yup, that's what I said ;)
> so you have to go in the Installation example on Ubuntu Server to get the commands to type in

It's just a bit weird because you would think that the example is only a `practice exercise`, and there won't be important steps that wouldn't be told before. You see what I mean?

The reason why I was surprised is that I'm running a Debian server so I didn't care about the Ubuntu example section, I thought that just following the steps in [Installation on a dedicated server](https://www.sonerezh.bzh/docs/en/installation.html#installation-on-a-dedicated-server) would be enough.

**Comment by lGuillaume124** [comment]
Indeed the documentation is not clear enough.

**Comment by MightyCreak** [comment]
There too I can help if you point me to the right folder ;)
