### ISSUE TITLE
Move the development branch in master

### ISSUE THREAD

**Issue by MightyCreak** [Sonerezh/sonerezh#243]
All the other git projects uses the master branch as the stable development branch. That's why most of the PR from other users are based on master all the time.

What I'm used to is creating a branch from master, do my fix or feature, test it, and PR or merge it in master. At some point, when we want to stabilize, we only merge fixes in master. And once master is stable, we create a tag at the commit with the version name. If fixes need to be added to the release, we branch from the commit tag and cherry-pick the fix in this branch.

What do you think?

**Comment by atomiix** [comment]
We recently added a [contributing guide](https://github.com/Sonerezh/sonerezh/blob/master/CONTRIBUTING.md) to the source.
It clearly tells to PR on the dev branch.

Also, we didn't create our own workflow, we are following [this one](http://nvie.com/posts/a-successful-git-branching-model/).

In this way, master is **always** stable.

**Comment by MightyCreak** [comment]
I didn't know this workflow. It's fine by me if it's documented.

Closing...
