### ISSUE TITLE
I can't add a song to a playlist anymore

### ISSUE THREAD

**Issue by tantic** [Sonerezh/sonerezh#250]
Hello,

I've upgraded my sonerezh to the 1.1.3 version and now I can't add 2 songs to a playlist (if I create the playlist I can add 1 song). When I click on the add button nothing happen.

In the chromium console I've got this message
`An invalid form control with name='data[Playlist][title]' is not focusable.`

I use sonerezh via Yunohost.

Thanks in advance (and thanks for the soft, it's amazing)

**Comment by pacija** [comment]
Hi,

I've just upgraded to 1.1.3 and am experiencing the same problem, from both Chrome on Windows and Chromium on FreeBSD.

**Comment by razdoris** [comment]
bonjour,

j'ai le même problème

hello,

i've the same problem.

**Comment by Denniz** [comment]
Still having this issue, clean install,
Error in browser console: `An invalid form control with name='data[Playlist][title]' is not focusable.`

**Comment by EDNI** [comment]
The [fix](https://github.com/Sonerezh/sonerezh/commit/f7baa07ea265a9f33857f0e5c164854f349f1126) was done on the development branch but you can modify it manually (by removing the lines in red and adding the lines in green). It worked just fine for me.

**Comment by Denniz** [comment]
Thanks @EDNI, this worked indeed.
