### ISSUE TITLE
Error message showing HTML

### ISSUE THREAD

**Issue by maxengel** [Sonerezh/sonerezh#251]
please see the attached.
<img width="1280" alt="screen shot 2016-12-25 at 11 11 53 pm" src="https://cloud.githubusercontent.com/assets/810989/21484120/9ad00094-cb5b-11e6-82c4-0ba882fd61c4.png">

**Comment by lGuillaume124** [comment]
Already fixed in 1.1.3. (https://github.com/Sonerezh/sonerezh/commit/e49e692afd1bbee84c115b8e5e4639652280d410#diff-c0923fa926683fc4706df7cd7fdddef7)

**Comment by maxengel** [comment]
FWIW, this happened for me with the latest Docker pull.

**Comment by lGuillaume124** [comment]
Indeed, the Docker image is not up to date.
