### ISSUE TITLE
In En translation, issue on the homepage

### ISSUE THREAD

**Issue by maxengel** [Sonerezh/sonerezh#256]
"Indicate where is your music library"

should be

"Indicate where your music library is"

**Comment by MightyCreak** [comment]
Fixed in Sonerezh/docs#9

**Comment by MightyCreak** [comment]
Because it took me some time to understand, it's in https://www.sonerezh.bzh/

**Comment by MightyCreak** [comment]
Fixed in PR Sonerezh/www#2
