### ISSUE TITLE
Support direct FLAC streaming on Firefox & Chrome

### ISSUE THREAD

**Issue by MightyCreak** [Sonerezh/sonerezh#257]
Hi!

I was thinking that maybe its possible technically to have the best of both worlds: stream the FLAC directly if the browser supports it, or convert the file with ffmpeg.

Especially thanks to the fallback feature of the `<audio>` tag [1], it would be possible to write something like that:

```html
<audio>
  <source src="original_url.flac" type="audio/flac">
  <source src="converted_url.ogg" type="audio/ogg">
  I'm sorry; your browser doesn't support any of the proposed audio formats.
</audio>
```

In the Szh preferences, everything is already here. If the admin wants to save the bandwidth, he can activate the conversion, otherwise if he prefers sound quality, he can uncheck FLAC (that's the only thing to change in the preferences). In any case, if the client doesn't support FLAC he will fallback to the OGG conversion.

I honestly think that lossless streaming could attract quite a lot of audiophiles.

What do you think??

[1] https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats

**Comment by MightyCreak** [comment]
Thinking of it, I think this idea could expand to other audio formats.
The algorithm to write the `<audio>` tag would look like that:

```php
<?php
  $song_raw_url = get_song_raw_url($songId);
  $audio_format = get_audio_format($song_raw_url);
  $song_urls = array();
  if (can_read_audio_format($audio_format))
    $song_urls[$song_raw_url] = $audio_format;
  list($song_converted_url, $converted_audio_format) = get_song_converted_url($song_raw_url);
  if ($song_converted_url != null)
    $song_urls[$song_converted_url] = $converted_audio_format;
?>
<audio>
<?php foreach ($song_urls as $url => $audio_format): ?>
  <source src="<?= $url ?>" type="<?= $audio_format ?>">
<?php endforeach ?>
  I'm sorry; your browser doesn't support any of the proposed audio formats.
</audio>
```

Thanks to this, the admin can say which audio formats he allows for direct streaming, depending on the server bandwidth and space. And he can define the conversion audio format whether if the format isn't supported by the client, or if the admin doesn't want to stream this audio format.

In the preference, we would have two sections:
1. A list of check-boxes for the allowed streamed audio formats (mp3, ogg, wav, flac, aac, alac, ...);
2. The fallback/conversion audio format and settings

**Comment by MightyCreak** [comment]
And now Chrome 56 will have FLAC decoding as well (french article: https://www.nextinpact.com/news/102879-chrome-56-beta-gere-nativement-codec-audio-flac.htm)

**Comment by flyinva** [comment]
Firefox [will support flac](https://bugzilla.mozilla.org/show_bug.cgi?id=1195723) in next release scheduled in few days

**Comment by lGuillaume124** [comment]
Indeed, great news!
As the "flac" checkbox is hard checked on the settings page, you have to directly edit the database until we fix it. Something like:

```sql
UPDATE `settings` SET `convert_from` = 'aac' WHERE `id` = 1;
```

should be fine.

**Comment by TiJof** [comment]
It's fine with this sql request !
Thank you @lGuillaume124

**Comment by MightyCreak** [comment]
@lGuillaume124 what do you think about the `<audio>` fallback proposition? So that there are more than one source, helping with browser that can't play FLAC codec (thinking about mobile browsers, old browser versions and, of course, Edge) ;)

**Comment by nicman23** [comment]
any progress on this? i am in the latest tag and i would like this to work without the mysql hack :/

**Comment by nicman23** [comment]
?
