### ISSUE TITLE
Conversion not working

### ISSUE THREAD

**Issue by Diskutant** [Sonerezh/sonerezh#266]
Autoconversion is not working for some reason.

avconv is installed:

	avconv version 11.8-6:11.8-1~deb8u1+rpi1, Copyright (c) 2000-2016 the Libav developers
	  built on Oct  8 2016 02:37:00 with gcc 4.9.2 (Raspbian 4.9.2-10)
	Hyper fast Audio and Video encoder
	usage: avconv [options] [[infile options] -i infile]... {[outfile options] outfile}...

	Use -h to get full help or, even better, run 'man avconv'

error.log:

	2017-02-04 17:35:03 Error: [NotFoundException] The requested file was not found
	Request URL: /sonerezh/songs/download/6
	Stack Trace:
	#0 /var/www/html/sonerezh/app/Controller/SongsController.php(596): CakeResponse->file('/var/www/html/s...', Array)
	#1 [internal function]: SongsController->download('6')
	#2 /var/www/html/sonerezh/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(SongsController), Array)
	#3 /var/www/html/sonerezh/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
	#4 /var/www/html/sonerezh/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(SongsController), Object(CakeRequest))
	#5 /var/www/html/sonerezh/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
	#6 {main}

Running on Raspberry Pi

	uname -a
	Linux raspberrypi 4.4.38-v7+ #938 SMP Thu Dec 15 15:22:21 GMT 2016 armv7l GNU/Linux

Tried with sonerezh release 1.1.3 and with git master

**Comment by MightyCreak** [comment]
Maybe you mean "conversion" ;)

**Comment by Diskutant** [comment]
whoopsie 😅
can't change the title though

**Comment by MightyCreak** [comment]
Does your file path has special characters?

**Comment by Diskutant** [comment]
Tried a file without any special characters:

	/mnt/musicJupiter/ASP Test/01-01 Intro.flac

Same error.

**Comment by MightyCreak** [comment]
Does it work well on regular mp3 files?
Is the problem coming from the fact that avconv wasn't found or because avconv wasn't able to convert the audio file?

**Comment by MightyCreak** [comment]
You can also verify if PHP can access the avconv binary (see https://github.com/Sonerezh/sonerezh/issues/211#issuecomment-233871325)

**Comment by atomiix** [comment]
Hi, 

Seems to be the same issue as this one : #261.

**Comment by Diskutant** [comment]
Thanks atomiix, this did it https://github.com/Sonerezh/sonerezh/pull/259/commits/b8eaad020cb3c9079f33f82a81a361938a9df4f7

**Comment by MightyCreak** [comment]
It's not already in the release?? @atomiix some stuff really need to be patched on the current release. Now that it's merged into dev, can't you cherry-pick it in master?
