### ISSUE TITLE
Ability to download tracks

### ISSUE THREAD

**Issue by nodiscc** [Sonerezh/sonerezh#27]
Hi! Thanks for the awesome project.

I miss the ability to download a track/multiple tracks. There could be a download button next to the play/enqueue buttons next to each track.

Bonus: When using the download button on an album, the album could be zipped (like owncloud does) before offering it to download as a single file.

**Comment by lGuillaume124** [comment]
Hi,

Don't worry it will be part of a major release :)
But we don't know wich one :/

**Comment by lGuillaume124** [comment]
First we will add the possibility to download a single song, for the next minor release (1.1.2).
Then you will be able to download a full album or a full artist in the next major release (1.2.0). We choose to do this because it will introduce new PHP dependencies to generate zip files :)
