### ISSUE TITLE
Albums with the same name are not listed /albums

### ISSUE THREAD

**Issue by ThecaTTony** [Sonerezh/sonerezh#270]
Albums with the same name are not listed more than once in /album being of different artists. Example: Gratests Hits, Unplugged...

Only the first imported album is listed:

Eric Clapton - Unplugged <--
Aerosmith - Unplugged

They also do not appear in "Recently added" when a dupe album name is imported.

**Comment by fcharlier** [comment]
I proposed a fix (see #236) some time ago for this issue but it was reverted du to apparently some performance issues (don't see any running in mysql/mariadb)

**Comment by ThecaTTony** [comment]
Thanks for the help @fcharlier but that fix hang my mariadb instance.

**Comment by gs11** [comment]
Fix available in pull request #304

**Comment by kuroidoruido** [comment]
@lGuillaume124 This issue seems to be fixed. I think you can close it :)
