### ISSUE TITLE
Getting "Undefined index: id [APP/Model/User.php, line 152]" During Installation

### ISSUE THREAD

**Issue by GaneshKandu** [Sonerezh/sonerezh#277]
Hi Trying to install 
but getting "Undefine index: id" notice with blank page

- 1
**Notice (8)**: Undefined index: id [**APP/Model/User.php**, line **152**]
**Warning (2)**: Cannot modify header information - headers already sent by (output started at lib/Cake/Utility/Debugger.php:794) [**CORE/Cake/Network/CakeResponse.php**, line **449**]
- 2
what files and directories should be Writable for installation ??

**Comment by monomops** [comment]
Probably user of webserver is not allowed to write to music folder

**Comment by GaneshKandu** [comment]
"Music" folder is Writable with 777 permission

May be because user does not exist at installation time  and script trying to fetch user detail to validate is it Admin

**Comment by gs11** [comment]
Replicated the issue, appears when using Postgres
