### ISSUE TITLE
Attribut dupliqué "required" sur la page "login"

### ISSUE THREAD

**Issue by griffin0** [Sonerezh/sonerezh#29]
Sur la page "login", l'attribut HTML required (valorisé à "required") est dupliqué pour les 2 balises input ("UserEmail" et "UserPassword")

Toutefois, cela ne génère aucun problème d'utilisation.

**Comment by lGuillaume124** [comment]
Salut,

C'est CakePHP qui génère le code HTML sur ce formulaire donc on ne peut rien faire :)
