### ISSUE TITLE
Not working with nginx

### ISSUE THREAD

**Issue by bichomen** [Sonerezh/sonerezh#305]
Hello, I am desperate I can not make Sonerezh work in my subdomain "musica" I put the configuration file of nginx of the subdomain:

`server {
                ## Escucha en el puerto 80 (HTTP)
                listen 80;

                server_name musica.mydomain.com;
                root /srv/www/musica/app/webroot;

                access_log /var/log/nginx/musica_access.log;
                error_log /var/log/nginx/musica_error.log;

                index index.php;

                location / {
                        try_files $uri $uri/ /index.php?$args;
                        expires 14d;
                        add_header Cache-Control 'public';
                }

                location ~ \.php$ {
                        try_files  $uri =404;
                        fastcgi_split_path_info ^(.+\.php)(/.+)$;
                        fastcgi_pass unix:/var/run/php/musica.sock;
                        #fastcgi_param SCRIPT_FILENAME /srv/www/musica/app/webroot/$fastcgi_script_name;
                        fastcgi_index index.php;
                        include fastcgi_params;
                }
}
`
Subdomain PHP configuration file:

`listen = /var/run/php/musica.sock
listen.backlog = 4096
listen.owner = bichomen
listen.group = bichomen
listen.allowed_clients = 127.0.0.1
listen.mode=0660

; Unix user/group of processes
user = musica
group = musica

; Choose how the process manager will control the number of child processes.
pm = dynamic
pm.max_children = 75
pm.start_servers = 10
pm.min_spare_servers = 5
pm.max_spare_servers = 20
pm.max_requests = 500

; Pass environment variables
env[HOSTNAME] = $HOSTNAME
env[PATH] = /usr/local/bin:/usr/bin:/bin
env[TMP] = /tmp
env[TMPDIR] = /tmp
env[TEMP] = /tmp

; host-specific php ini settings here
; php_admin_value[open_basedir] = /var/www/DOMAINNAME/htdocs:/tmp

env[HOSTNAME] = $HOSTNAME
env[PATH] = /usr/local/bin:/usr/bin:/bin
env[TMP] = /tmp
env[TMPDIR] = /tmp
env[TEMP] = /tmp
php_admin_value[open_basedir] = /srv/www/musica/app/webroot/
php_admin_value[date.timezone] = Europe/Madrid

chroot =
chdir = /srv/www/musica/app/webroot
`

**Comment by PixiBixi** [comment]
Hola señor!

Try this server block

```
server {
    listen 80;

server_name music.ndd.tld;
root /var/www/sonerezh/app/webroot;

access_log /var/log/nginx/sonerezh.access.log;
error_log /var/log/nginx/sonerezh.error.log;

index index.php;

location / {
    try_files $uri $uri/ /index.php?$args;
}

# Serve static images from resized folder
location ~* \/([^\/]+_[0-9]+x[0-9]+\.[a-z]+) {
    try_files /img/resized/$1 /index.php?$args;
    expires 14d;
    add_header Cache-Control 'public';
}

location ~ \.php$ {
    try_files $uri =404;
    fastcgi_index index.php;
    fastcgi_pass unix:/var/run/php5-fpm.sock;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    include /etc/nginx/fastcgi_params;
}
}
```

It was working for me

**Comment by bichomen** [comment]
Thank @PixiBixi, but not working

**Comment by PixiBixi** [comment]
Did you applied the correct rights ?

chown -R www:data:www-data /var/www...

Could you send your error_log ?

**Comment by bichomen** [comment]
Modify in the PHP configuration file this line:
`php_admin_value[open_basedir] = /srv/www/musica/app/webroot/`

For this other:
`php_admin_value[open_basedir] = /srv/www/musica/app/webroot/:/tmp/:/`

And now tell me this:
![sonerezh](https://cloud.githubusercontent.com/assets/20316285/26206787/05348892-3be6-11e7-8a87-04b5084bae4b.png)

**Comment by bichomen** [comment]
My user for this subdomain is "musica" and for all files and folders their permissions are 755 and 644

**Comment by bichomen** [comment]
My log:

> 2017/05/18 16:27:54 [error] 1580#1580: *2138 open() "/srv/www/musica/install" failed (2: No such file or directory), client: 195.16.143.6, server: musica.mydomain.com, request: "GET /install HTTP/1.1", host: "musica.mydomain.com"

**Comment by PixiBixi** [comment]
php_admin_value[open_basedir] = /srv/www/musica/app/webroot/
chdir = /srv/www/musica/app/webroot

These values are wrong i think

**Comment by bichomen** [comment]
Thank @PixiBixi 

I have changed:
`chdir = /srv/www/musica/app/webroot`

by:
`chdir = /srv/www/musica`

I have also modified the nginx settings:
`server {
                ## Escucha en el puerto 80 (HTTP)
                listen 80;

                server_name musica.bichomen.com;
#               root /srv/www/musica/app/webroot;

                access_log /var/log/nginx/musica_access.log;
                error_log /var/log/nginx/musica_error.log;

                index index.php;

                location / {
                        alias /srv/www/musica/app/webroot;
                        #fastcgi_param PHP_VALUE open_basedir="/srv/www/musica/app/webroot";
                        fastcgi_param PHP_VALUE open_basedir="/srv/www/musica/:/srv/www/musica/Musica";
                        try_files $uri $uri/ /index.php?$args;
                        expires 14d;
                        add_header Cache-Control 'public';
                }

                # Serve static images from resized folder
                location ~* \/([^\/]+_[0-9]+x[0-9]+\.[a-z]+) {
                        try_files /img/resized/$1 /index.php?$args;
                        expires 14d;
                        add_header Cache-Control 'public';
                }


                location ~ \.php$ {
                        alias /srv/www/musica/app/webroot/$1;
                        fastcgi_split_path_info ^(.+\.php)(/.+)$;
                        fastcgi_pass unix:/var/run/php/musica.sock;
                        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                        fastcgi_param PATH_INFO $fastcgi_path_info;
                        fastcgi_param modHeadersAvailable true; #Avoid sending the security headers twice
                        try_files $uri =404;
                        fastcgi_index index.php;
                        include fastcgi_params;
                        fastcgi_param CAKEPHP_DEBUG 1;
                }
}
`

But everything stays the same :-(

**Comment by PixiBixi** [comment]
Hmm have you got a new error, or it's still the same?

**Comment by bichomen** [comment]
It looks for the folder or file "install" and because it does not find it it throws the error "404 not found"

:-( :-(

**Comment by bichomen** [comment]
Well after many tests and errors I configured the server with support ssl http2.

But when I access the subdomain, instead of loading the page, I try to download it:

![captura de pantalla de 2017-05-30 16-51-41](https://cloud.githubusercontent.com/assets/20316285/26589637/c9c3dff2-4558-11e7-8549-e0511fabc9ab.png)

**Comment by bichomen** [comment]
At the end changing the name of the folder:

Sonerezh ----- >> music

And restarting the server started working
