### ISSUE TITLE
[privacy] Do not hotlink images from flattr.com, paypalobjects.com

### ISSUE THREAD

**Issue by nodiscc** [Sonerezh/sonerezh#31]
I'm fine with donate buttons in the settings view, but please use a local `src=` for these and don't fetch them from paypalobjects.com and flattr.com. This leaks the URL of your Sonerezh instance to these services and harms user privacy.

https://github.com/Sonerezh/sonerezh/blob/563276d57a20781a4cdfd0163b8b750191ca2c55/app/View/Settings/index.ctp#L90
https://github.com/Sonerezh/sonerezh/blob/563276d57a20781a4cdfd0163b8b750191ca2c55/app/View/Settings/index.ctp#L97

**Comment by lGuillaume124** [comment]
You are absolutely right.
