### ISSUE TITLE
How do I change the icon of the Sonerez?

### ISSUE THREAD

**Issue by bichomen** [Sonerezh/sonerezh#311]

**Comment by gs11** [comment]
Which icon do you mean and why would you want to do that?
Without extra development you could just move your file with the same filename to the location of the image you want to change.

**Comment by EDNI** [comment]
I don't know if it answers your question but the "Sonerezh" in the nav bar is defined on line 48 in /app/View/Layouts/default.ctp

<?php echo $this->Html->link("your custom name here", array('controller' => 'songs', 'action' => 'index'), array('class' => 'navbar-brand')); ?>

to change the favicon, the icon that shows on the left of the tab you can change the favicon.ico in /app/webroot/

by default, it's the CakePHP icon, you can create you own on Gimp or here http://www.favicon.cc/

**Comment by bichomen** [comment]
Thank you!!

**Comment by EDNI** [comment]
My pleasure! If you want to make other cosmetic changes the CSS is pretty clean. On some open source app/frameworks/cms, with all the style cheats it can get pretty messy but here the devs did an amazing KISS job. You can really easily change the colors on the style.css file.
