### ISSUE TITLE
Changing Charset. 

### ISSUE THREAD

**Issue by tridiumcontrols** [Sonerezh/sonerezh#320]
Trying to add russian music to sonerezh, it imports just fine, and I can play it back, but the text is scrambled, see screenshot. I know this is a charset issue but do not know if this is a nginx, or php or sonerezh issue and if where I can adjust the charset. 

Runing Sonerezh on Ubuntu 16.04 LTS, with latest version of NginX, PHP 7, MariaDB.

Screenshot:
https://ibb.co/cGqxkF

**Comment by gs11** [comment]
Is there any public domain track with Russian metadata you could share for testing purposes?

**Comment by tridiumcontrols** [comment]
Yes, here's a dropbox link to one of the songs. 

https://www.dropbox.com/s/lniyab4z60gdl58/%D0%93%D0%BE%D1%81%D0%BF%D0%BE%D0%B4%D0%B8%20%D0%91%D0%BE%D0%B6%D0%B5%20%D0%BF%D0%BE%D0%BC%D0%B8%D0%BB%D1%83%D0%B9.mp3?dl=0

**Comment by gs11** [comment]
Thanks, the characters look fine here.
![image](https://user-images.githubusercontent.com/6217068/28361780-2048eb90-6c7a-11e7-92fc-9d2279ae44a5.png)

However, the import process says "Metadata are unreadable or empty. Trying to import anyway...".
Also, the mp3 file only contains ID3v1 tags without any russian characters...just "no artist/no title/Audio Track 09".
I'm guessing the title is somehow parsed from the filename but there's something strange going on with the import process:

**Database source_path: /data/Music/sonerezh/ Боже помилуй.mp3
Real source path: /data/Music/sonerezh/Господи Боже помилуй.mp3**

**Comment by tridiumcontrols** [comment]
Hmm, Interesting, Try this one, The link below is the song from my original post, 

https://www.dropbox.com/s/cjzgpbscvz6arfe/01-%D0%A2%D0%B2%D0%BE%D1%8F%20%D0%BB%D1%8E%D0%B1%D0%BE%D0%B2%D1%8C.mp3?dl=0

Also, when I "GET Info" using mac os x, it also can't decipher the artist info. 

https://ibb.co/hup5s5

**Comment by MightyCreak** [comment]
> Database source_path: /data/Music/sonerezh/ Боже помилуй.mp3
> Real source path: /data/Music/sonerezh/Господи Боже помилуй.mp3

Feels like a regular `strlen` has been used on a UTF8 string...

**Comment by gs11** [comment]
No editor/player of mine seems to be able to show the tags correctly. However, some digging in the files reveals that the ID3v2 tag encoding is Windows-1251.

**Comment by gs11** [comment]
Looking further into the issue, it seems that using Windows-1251 encoding for IDv3 tags is not valid:
https://stackoverflow.com/questions/16941269/gibberish-result-reading-unicode-tags-using-mp3agic-in-java/20000353

I'd recommend you into converting these tracks using Unicode tags instead. There seems to be a number of tools that provides this functionality.

**Comment by tridiumcontrols** [comment]
Thanks for the help, found few utilities will give them a go tonight.
