### ISSUE TITLE
Activating Shuffle Mode halts music playback.

### ISSUE THREAD

**Issue by tridiumcontrols** [Sonerezh/sonerezh#321]
Hi, 

I'm running latest version of sonerezh (1.1.3) on ubuntu 16.04 and nginx/1.10.3 web server with PHP 7.0.18-0ubuntu0.16.04.1, and mariaDB 10.0.29-MariaDB-0ubuntu0.16.04.1. 

Running into an issue whenever I activate shuffle mode, playback won't start, I invoke the play/pause button and player tries to play, but doesnt, when I try to skip to another song, the song loads in the player, and playback doesn't start, as soon as I de-activate shuffle mode, and manually select one of the songs, then playback resumes and working just fine. 

See attached screencaps.

Right after activating shuffle mode: https://ibb.co/bRO3Uk
Skipped to next song with shuffle mode activated: https://ibb.co/c0xQaQ
Shuffle mode de-activated, and manually selected a song from the list, playback resumes: https://ibb.co/dFMU25

**Comment by gs11** [comment]
Tried to reproduce the issue but no luck. Can you check the javascript console for any errors?
Also, is a song playing when you activate shuffle mode?

**Comment by tridiumcontrols** [comment]
Yes a current song is playing when activating shuffle mode, either way, if there is no song playing and I activate shuffle mode and try to start to play the song, song gets loaded in the player, and does not play. 

Where would I check the javascript console? in my browser? or on the server where sonerezh is installed?

**Comment by gs11** [comment]
There's javascript console in your browser. For example in Firefox **Developer ->Web Console** or Chrome **More Tools -> Developer tools**

**Comment by tridiumcontrols** [comment]
Right, 

See screencap link below, can't be decoded messages, and a 404, each time i press skip the error comes up, and to resume playback I have to refresh the page and then re-select a track and it plays.

Can't be decoded messages with shuffle mode activated, https://ibb.co/hY2gh5
this one is odd, I refreshed the page, and searched for the same file 10 - Track 10.mp3 and some tracks show the duration and others do not. https://ibb.co/m5YbFQ

**Comment by gs11** [comment]
Glad you got it sorted out!
