### ISSUE TITLE
Lazyloading problem with Sonerezh and nginx reverse proxy

### ISSUE THREAD

**Issue by kuroidoruido** [Sonerezh/sonerezh#324]
Hello,

I just installed a Sonerezh with the official Docker image. My Sonerezh container expose has the following port redirection 11080:80 so i can access to it directly through mydomain.com:11080. I configured Sonerezh throught mydomain.com:11080. 

I want to access to my Sonerezh with a Nginx reverse proxy that proxy_pass all requests from mydomain.com/sonerezh to localhost:11080. And i can access to Sonerezh but the lazyloading of the *.js, *.css, etc. not working because it try to load directly through mydomain.com 

example : https://mydomain.com/css/bootstrap.min.css instead of https://mydomain.com/sonerezh/css/bootstrap.min.css

My Nginx configuration : 
```
    location /sonerezh {
	rewrite /sonerezh(.*) /$1 break;
        proxy_pass		http://localhost:11080;
	proxy_redirect		off;
	proxy_set_header	Host $host;
    }
```

I also tried to add this to force redirection 
```
location / {
	rewrite /sonerezh(.*) /$1 break;
        proxy_pass		http://localhost:11080;
	proxy_redirect		off;
	proxy_set_header	Host $host;
}
```
it let the browser access to all *.js, *.css etc. files but it create another error : the url in my browser is setted to "mydomain.com/docker-install", i have the top bar with the music player, but instead of songs list i have the message "An Internal Error Has Occurred. Error: An Internal Error Has Occurred.". 

Someone can give me some help please ?

**Comment by nkoep** [comment]
Did you ever figure out how to get this running? I'm facing a similar issue where I can't move past the docker-install landing page cause it redirects to `domain.com/docker-install` instead of `domain.com/sonerezh/docker-install` after submitting the form.

**Comment by gs11** [comment]
Hi, please see this PR for a fix: https://github.com/Sonerezh/docs/pull/10
