### ISSUE TITLE
Is sonerezh still maintained?

### ISSUE THREAD

**Issue by Kabouik** [Sonerezh/sonerezh#338]
I know that sonerezh is already working, but I see that the last change in this repository happened 2 years ago, so I am wondering if sonerezh is still actively maintained. I love the UI, I hope the project is not abandoned.

**Comment by dadall** [comment]
If I may, and this is surely not polite at all, you should consider using [Funkwhale](https://code.eliotberriot.com/funkwhale/funkwhale) from now.

**Comment by Angristan** [comment]
See #297

**Comment by Kabouik** [comment]
Thanks, I didn't know about the rework under progress.

**Comment by MightyCreak** [comment]
Will be fixed with #339
