### ISSUE TITLE
/import request black-holed

### ISSUE THREAD

**Issue by MightyCreak** [Sonerezh/sonerezh#341]
Hi!

I just reinstalled Sonerezh from scratch, it was working before (on @gs11's fork), but I get an error now when I want to import my albums (I tried with only one album, I get the same result).

I can access the /import page, but when I click on Update, I get a HTTP 400 answer.
Looking at the request's answer, I get an HTML text which basically can be summed up to:

    The request has been black-holed
    The requested address '/import' was not found on this server.

I'm on Debian 8, with nginx 1.10.3, PHP 5.6.36, and MySQL 14.14.

**Comment by MightyCreak** [comment]
Here is the request:

```
POST /import HTTP/1.1
Host: sonerezh.foolstep.com
User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0
Accept: */*
Accept-Language: fr-FR,fr;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: https://sonerezh.foolstep.com/import
Cookie: Sonerezh=##scrambled##; SonerezhCookie[lang]=Q2FrZQ%3D%3D.yZ6K; SonerezhCookie[auth]=##scrambled##
Connection: keep-alive
Content-Length: 0
```

Here is the answer header:

```
HTTP/2.0 400 Bad Request
server: nginx/1.10.3
date: Sun, 26 Aug 2018 21:15:59 GMT
content-type: text/html; charset=UTF-8
content-length: 8343
X-Firefox-Spdy: h2
```

**Comment by MightyCreak** [comment]
Last update:
I tried with @gs11's fork, on branch `development-new` which is synced on v1.2.0 and it works. I think there's no changes between gs11's branch and the `1.2.0` tag here, so I would say that the problem comes from the commits between 1.2.0 and 1.2.1.

**Comment by lGuillaume124** [comment]
Yes it is.

**Comment by lGuillaume124** [comment]
Sorry for that, it comes from the latest CakePHP release : https://book.cakephp.org/2.0/en/appendices/2-10-migration-guide.html#components

> ``SecurityComponent`` will blackhole post requests that have no request data now. This change helps protect actions that create records using database defaults alone.

And the ``/import`` JS sends an empty POST request to trigger the import process. I'll try to fix it as soon as possible.

**Comment by MightyCreak** [comment]
Thanks! ;)
