### ISSUE TITLE
HTTP ERROR 500 for 1.22

### ISSUE THREAD

**Issue by loso20p** [Sonerezh/sonerezh#342]
HTTP ERROR 500 page isnt working.

i tried tried 1.20 and the install page comes up but 1.22 no install page and HTTP ERROR 500

is it missing a file or something?

**Comment by lGuillaume124** [comment]
That's weird. I've double checked ``/install`` before pushing 1.2.3 :cry: 

Let's re-open the issue.

**Comment by lGuillaume124** [comment]
Are you using a webserver like Apache or NGINX?

**Comment by MasThoDont** [comment]
Yes I'm using Apache.

**Comment by lGuillaume124** [comment]
> I run Sonerezh on a https domain, maybe that is the problem.

Nope.

**Comment by MasThoDont** [comment]
I find that went wrong.

In the release 1.2.1, the file .htaccess was deleted.
So I restored it on my server and the 1.2.3 version is working fine. (with the previous change in _index.php_)

**Comment by lGuillaume124** [comment]
Good catch. I'll fix both of them. Thank you a lot!
