### ISSUE TITLE
Add installation steps in the README

### ISSUE THREAD

**Issue by MightyCreak** [Sonerezh/sonerezh#344]
It's nice that there is a documentation in the official site on how to install Sonerezh, but I think it would be nice to also add the steps in the README.md file. If you're ok with that I can make a PR.

I would also like to add steps to install from git, but I don't know how to set up Sonerezh now that it's using composer; I don't know the command I should use (on my site, there is a composer.phar that can be executed in order to make upgrades etc).

**Comment by lGuillaume124** [comment]
No problem, I'll be glad to merge such a PR.

To install Sonerezh from Git the steps didn't change a lot. It could be something like:

```
$ git clone https://github.com/Sonerezh/sonerezh.git
$ cd sonerezh
$ composer install
```

I'm running Ubuntu on my laptop so I just installed composer using ``apt install composer`` and it is available _as is_.

But you can find other ways to install Composer on [getcomposer.org](https://getcomposer.org/doc/00-intro.md#locally).

**Comment by MightyCreak** [comment]
Just started this morning :smile:

**Comment by lGuillaume124** [comment]
Oh sorry!

**Comment by MightyCreak** [comment]
No worries, I wasn't deep into the changes :smile:
