### ISSUE TITLE
Language configuration

### ISSUE THREAD

**Issue by Tos26** [Sonerezh/sonerezh#358]
hello,

I try to have my sonerezh in french but it's still english despite my configuration (sonerezh 1.2.4):
In the file /sonerezh/app/Config/bootstrap.php I put this :
/**
 * Default application language
 */
Configure::write('Config.language', 'fra');

Is it the right way to set the language?

Thank you for your answer.

**Comment by lGuillaume124** [comment]
Hello,

Sonerezh uses the ``Accept-Language`` HTTP header to define which language should be loaded.

https://github.com/Sonerezh/sonerezh/blob/22b75a3e5f2bd6b08e85df96443799b52b34d56b/app/Controller/AppController.php#L156-L183

**Comment by Tos26** [comment]
Thanks Guillaume,

I removed the cookies related to my site in my firefox and now it's ok.
I don't understand why sonerezh switched to english, firefox is configured in french.

But no matter, all is ok now.

Thank you again and congratulations for this app, very useful for me and with a lot of potentiality.
