### ISSUE TITLE
Disconnected while listening music

### ISSUE THREAD

**Issue by jbleuzen** [Sonerezh/sonerezh#43]
This is an important enhancement to me, because it drives me crazy that my music stops and I have to reconnect...
Should add a checkbox on login to enable remember -me or something like that.

**Comment by p1rox** [comment]
It is in the roadmap https://www.sonerezh.bzh/docs/en/roadmap.html

**Comment by jbleuzen** [comment]
Thanks didn't noticed it in the roadmap...
