### ISSUE TITLE
NULL entries in the 'songs' table.

### ISSUE THREAD

**Issue by Tangeek42** [Sonerezh/sonerezh#44]
Hi,

Yes, I know I already sent an e-mail showing this bug (I'm the same Tangeek and at the time I hadn't notice the "Issues" button in GitHub, sorry... ._.), but I just want to open an issue here, just so it will be documented if someone has the same problem. Again, sorry for imposing myself like that. (You'll notice this time the screenshot doesn't weight over 2MB... ^^ )

So, the problem is that I have randomly some entries in the 'songs' table that are just NULL everywhere. Most of them are sequential, so I'm assuming it's related to something in my files during the scan, but I still haven't found what songs aren't listed yet (there's a lot of them :3). Another thing probably related is that the Songs count in the options page is ~25 lower than the entries count from MySQL, which is the same amount of NULL entries.

![export](https://cloud.githubusercontent.com/assets/11335279/6509225/273214ee-c35e-11e4-9624-cc0ebc54d3c7.png)

The songs actually appear in Sonerezh listing, but they aren't readable (they point to NULL...) and empty the queue. Since all of their fields are also at NULL, they're going straight to "Unknown" and I can't find out who they are. :/ 

I'm really hoping this is a real problem and not me missing something trivial... XD

**Comment by DiscoSeb** [comment]
I have the same problem and apparently it comes accented characters in filename (or folder name) when importing MP3 (ex: "01 - Oxygène I.mp3").
The extract of tags MP3 on a file whose name contains an accented character is problematic...

**Comment by lGuillaume124** [comment]
I think you have the same problem than #72 
Your problem should be fixed with commit bf47083dcd

**Comment by DiscoSeb** [comment]
Désolé je rebascule en français...
Pour moi le problème ne se situe pas au niveau des tags mais directement du nom du fichier car si je renomme le fichier cela fonctionne.
Je viens à l'instant de tester : dans un dossier, j'ai mis 1 mp3, dont le nom du fichier contient un accent "é" puis je vide la base et refait un update : la base contient un seul enregistrement avec des valeurs "null". 
Je renomme le fichier en retirant l'accent (remplacé par un "e") puis refait l'opération et là la base est correctement remplit, la chanson est disponible sur le site.
Entre les deux tests je n'ai pas touché aux tags MP3 qui sont d'ailleurs en UTF-8 (d'après TagScanner) donc pas de problème à ce niveau.

**Comment by lGuillaume124** [comment]
J'ai moi-même des pistes avec des accents qui fonctionnent sans problème. Pourriez-vous nous envoyer le fichier qui pose problème svp ?

hey@sonerezh.bzh

**Comment by Tangeek42** [comment]
(Désolé, je remonte)

J'ai honnêtement pas réussi à trouver lesquels ne fonctionnaient pas chez moi, mais je tiens à préciser que j'ai aussi des pistes avec accent, ou même écrites en japonais, qui fonctionnent sans souci.

**Comment by DiscoSeb** [comment]
Avec des accents dans les noms de fichiers ?
Et ton serveur Web tourne sur quel OS (Windows / Linux) ?
Chez moi c'est la combinaison des accents et du serveur web sous Windows qui semble poser problème...

**Comment by Tangeek42** [comment]
Oui oui, des accents ou des caractères japonais dans les noms, ainsi que dans les tags.
C'est un Apache qui tourne sous Debian. (Moi, original ? Ha, jamais)

Je sais que je suis pas d'une grande aide en venant dire "help ça marche" pas sans même donner plus d'infos, désolé. Je vais encore faire un scan en réinitilisant les ID et essayer d'y voir plus clair.
