### ISSUE TITLE
"Play all" button

### ISSUE THREAD

**Issue by nodiscc** [Sonerezh/sonerezh#47]
The title says it all. It's be nice to have a `Play all` button that plays your whole library. Combined to shuffle mode, just click and forget to play all your music.

**Comment by Niols** [comment]
Hacky solution: create a playlist that contain all songs.
I'm using [this little script](https://github.com/Niols/sonerezh-hacks/blob/master/playall_playlist.php).

By the way, this could be an easy solution to implement the "Play all": create a special playlist (maybe not stored in the database).

**Comment by fcharlier** [comment]
More ideas about the feature:

- play random songs
- play random albums
- start with n songs/albums, add new songs/albums when there are less than n songs in the playlist
- allow to insert other songs/albums and continue random play after

**Comment by lGuillaume124** [comment]
We have planned to redesign this part of Sonerezh, and use the IndexedDB API (https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) to relieve both the database and the bandwidth. More killer features will be conceivable then ;)

**Comment by lGuillaume124** [comment]
The queue has a better behavior now. It can:
* Play all the songs of a given band if you click on the 'play' button next to a band on the "Artists" view
* Play an entire album if you click on the 'play' button next to an album both on the "Albums" and the "Artists" views

If you click on the play button next to a song title, or if you double click on a song, depending on the view : 
* On the default one, the entire db will be added to the queue
* On the artists view, the band songs will be added
* The album songs will be added in the queue, on the Albums view

So I suppose I can close this issue now :)
