### ISSUE TITLE
The requested URL /sonerezh/install was not found on this server.

### ISSUE THREAD

**Issue by quentingosset** [Sonerezh/sonerezh#50]
fail :D it's good

**Comment by sputnick-dev** [comment]
When you have a problem with /install that means that you have to enable mod_rewrite in apache

**Comment by nodiscc** [comment]
It's also worth checking that your server doesn't have `AllowOverride None` in it's main config directive or else the RewriteRules in `.htaccess` won't work.

**Comment by p1rox** [comment]
@atomiix @lGuillaume124 You should talk about url rewriting in the doc, this is the second issue aout it (#41)

**Comment by lGuillaume124** [comment]
This is already written in the doc: https://www.sonerezh.bzh/docs/en/requirements.html

**Comment by p1rox** [comment]
I can effectively see it on the online version but not it the «Github version» :  https://github.com/Sonerezh/docs/blob/master/fr/requirements.rst . Normal ?

**Comment by nodiscc** [comment]
@p1rox because you're on the wrong branch
https://github.com/Sonerezh/docs/blob/1.0.0-beta/fr/requirements.rst

**Comment by p1rox** [comment]
Oups :p
