### ISSUE TITLE
Encountered 'An Internal Error Has Occurred' error

### ISSUE THREAD

**Issue by sputnick-dev** [Sonerezh/sonerezh#51]
When calling http://127.0.0.1/sonerezh/import I get 'An Internal Error Has Occurred.' in the web interface.

My directory takes 212GB of disk space.

If I test with only one small dir in a sub-path, all is working well.

My config : 

- archlinux_x86_64
- sonerezh git @ 510dd9d3c3487bb24489b1e2250debeabe9efcf1 (20150309)
- apache 2.4.12
- php 5.6.6

No error in apache logs.

**Comment by lGuillaume124** [comment]
Hi,

Do you have .wma files in your library?

**Comment by sputnick-dev** [comment]
I had yes, now converted to .ogg.

But I still get the same issue after deleting database.php and reconfiguring via the web UI and calling /import page.

**Comment by nodiscc** [comment]
@sputnick-dev also try going to the settings page, click `Clear the cache` and `Reset database`

**Comment by sputnick-dev** [comment]
I still get the same issue.

**Comment by sputnick-dev** [comment]
I still get the same issue.

I hope that sonerezh will be able to skip wrong files in the future and will report more concisely the errors encountered.

What about this report ?

**Comment by lGuillaume124** [comment]
Yes we will work on error management during the import process. Most of our import problems come from the third-party library that we use for extract metadata and we are thinking about remove it and develop our own solution instead.
