### ISSUE TITLE
Songs are not reading with opera v27.0.1689.76 (linux mint 17)

### ISSUE THREAD

**Issue by jerrywham** [Sonerezh/sonerezh#53]
When you want to listen a song, page is refreshed when reading begin.

**Comment by nodiscc** [comment]
Note that your browser has to support HTML5 audio, and have an available codec for the format you're trying to decode.

 * What are the results in the Audio/Codecs section of https://html5test.com/ using your Opera browser?
 * What is the format of the file you're trying to play?

**Comment by lGuillaume124** [comment]
+1 @nodiscc

**Comment by lGuillaume124** [comment]
As you can see, Opera does not support MP3 format:

![opera-browser_linux-mint](https://cloud.githubusercontent.com/assets/3330841/6605181/31ce07b2-c82e-11e4-88ac-0da22ea5614a.png)

(Opera 28.0.1750.40 on Linux Mint 17.1)

**Comment by jerrywham** [comment]
Ok
