### ISSUE TITLE
Install fails on Nginx in custom location

### ISSUE THREAD

**Issue by lowlow---** [Sonerezh/sonerezh#54]
Hi,

I'm struggling with the install in a custom location on nginx and more probably with nginx config ...

When I request http://myserver.com/custom_location/install, I'm offered to download an "install" file (which contains <?php phpinfo(); ?>). Then sonerezh config page is never reached.

Here is the server block I use:

```
server {
  listen 80;
  server_name myserver.com;
  root /path/to/www;

  location /custom_location/ {
    alias /path/to/install/;
    try_files $uri $uri/ /index.php?$args;
    index index.php;
    expires 14d;
    add_header Cache-Control 'public';

    location ~ ^/custom_location/(.+\.php)$ {
      fastcgi_index index.php;
      fastcgi_pass unix:/var/run/php-fpm/php-fpm.sock;
      include fastcgi_params;
      fastcgi_param SCRIPT_FILENAME /path/to/install/$1;
    }
  }
}
```

Any hints ?

Thanks

**Comment by lGuillaume124** [comment]
Hi,

Could you try this:

```
location ~ ^/custom_location/(.+\.php)$ {
            alias /path/to/install/app/webroot/$1;
            fastcgi_pass unix:/var/run/php-fpm/php-fpm.sock;
            fastcgi_index index.php;
            include fastcgi_params;
}
```

**Comment by lowlow---** [comment]
@lGuillaume124 
It doesn't solve the issue, the "install" file is still offered to download instead of being executed ...

**Comment by lGuillaume124** [comment]
Are you sure PHP-FPM is listenning on an unix socket?

**Comment by lowlow---** [comment]
PHP-FPM works, I've tested it with a phpinfo file ...

**Comment by lGuillaume124** [comment]
Hi, did you solve your issue?

**Comment by lowlow---** [comment]
Hi, I've test a fresh install on a dedicated vhost and I'm able to to make it working. 
However, I'm still struggling to make it working from a "custom_location". The following config is partially working:

    location /custom_location/ {
        alias /path/to/install/sonerezh/app/webroot/;
        try_files $uri $uri/ /index.php;
        expires 14d;
        add_header Cache-Control 'public';
     
        location ~ \.php$ {
            fastcgi_split_path_info ^/custom_location/(.+?\.php)(/.*)?$;
            fastcgi_pass unix:/var/run/php-fpm/php-fpm.sock;
            fastcgi_index index.php;
            include /etc/nginx/fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }

The index.php is processed, however the links to css and js files in the served page refer to the server root but not to "custom_location" and are therefore not found. 
Here is the index.php, I receive:
```
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        Errors    </title>
    <link href="/favicon.ico" type="image/x-icon" rel="icon" /><link href="/favicon.ico" type="image/x-icon" rel="shortcut icon" />    
	<link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css" />
	<link rel="stylesheet" type="text/css" href="/css/jquery.fs.selecter.min.css" />
	<link rel="stylesheet" type="text/css" href="/css/pace.css" />
	<link rel="stylesheet" type="text/css" href="/css/notify.css" />
	<link rel="stylesheet" type="text/css" href="/css/slider.css" />
	<link rel="stylesheet" type="text/css" href="/css/style.css" />
    <script type="text/javascript" src="/js/lazyload.min.js"></script>    <script id="queue-tr" type="text/html">
        <tr>
            <td class="truncated-name title"></td>
            <td class="truncated-name hidden-xs hidden-sm artist"></td>
            <td class="truncated-name visible-lg album"></td>
            <td class="text-right playtime-cell">
                <span class="song-playtime"></span>
                <span class="glyphicon glyphicon-play song-controls action-play" title="Play"></span><span class="glyphicon glyphicon-pause song-controls action-pause" title="Pause"></span><span class="glyphicon glyphicon-remove song-controls action-remove-from-queue" title="Remove from queue"></span>
            </td>
        </tr>
    </script>
</head>
<body>
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation" id="main-nav-bar">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle Navigation</span> <span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
            </button>
            <a href="/" class="navbar-brand">Sonerezh</a>        </div>
        <div class="collapse navbar-collapse">
```

I'm not sure this can be managed from nginx side, is there a way to serve static files with a relative path or a modified path from sonerezh side ?

**Comment by atomiix** [comment]
I think we had this problem when we setted up our demo instance. It was linked to [this nginx bug](http://trac.nginx.org/nginx/ticket/97). Here is how we solved it : 

    location /demo/ {
        alias /path/to/demo/app/webroot/;
        try_files $uri $uri/ /demo//demo/index.php?$args;

        location ~ ^/demo/(.+\.php)$ {
            alias /path/to/demo/app/webroot/$1;
            fastcgi_pass php5-fpm-sock;
            fastcgi_index index.php;
            include fastcgi.conf;
        }
    }

Yes it's tricky :D

**Comment by lowlow---** [comment]
Great ! This solved the issue for me.

Thanks

**Comment by atomiix** [comment]
Your welcome :)
