### ISSUE TITLE
Jump to letter in songs/artists/albums

### ISSUE THREAD

**Issue by nodiscc** [Sonerezh/sonerezh#57]
Scrolling down to arbitrary positions in songs/albums/artists lists takes a very long time, especially considering lazy loading of items, and couild get even worse on larger music collections (it's already difficult with 4000 songs).

When you want to browse songs that are far from the start of the list, you have to scroll down for a whiiiile before seeing something that you didn't play already (eg. if I want to see what's aroud Massive Attack in my library).

A simple group of links `#ABCDEFGHIJKLMNOPQRSTUVWXYZ` at the top of (or floated on the left-hand side) the list would allow easily jumping around different positions in your artists/songs/albums list (start browsing at R, jump back to G, sse what's at the end on X...)

**Comment by lGuillaume124** [comment]
We agree with you, we are working on it.

**Comment by ltGuillaume** [comment]
That, and picture this: when scrolling through artists/albums another song comes to mind and you'd like to add it to the queue, then head back to the list you were scrolling through. So you do a search, add the song and press the browser's back button. Oh sh*t, now you'll have to start from the top all over again. Anyway we could save the last position and return there?

**Comment by MightyCreak** [comment]
I know Deezer is using local href (i.e. `#`) for each actions: specific artist, specific album, etc... so when you use the browser previous/next buttons, you don't start over.

I don't know how it works behind that though.

**Comment by ltGuillaume** [comment]
Apparently this is a possibility, but I don't understand a single thing of it http://stackoverflow.com/a/1056896

I would reckon it should just be something like: Ajax pagination loads the next page? Then write the current page index to a session variable. Upon return to Home/Artists/Albums from another page, check for that session variable and jump to that page immediately.
