### ISSUE TITLE
No thumbnails

### ISSUE THREAD

**Issue by LucasAdam** [Sonerezh/sonerezh#6]
Hello, first of all great work guys ! 

My only issue is the following  : Every album I own has a jpg image supposed to be the cover of the album, in the same directory as the tracks. But Sonezezh doesn't seem to recognize any of them since I have the "no-cover" png diplayed for every album.

**Comment by lGuillaume124** [comment]
Hi,

That's because Sonerezh only analyze file's metadata and don't look for images in the file's directory. Unfortunately your files seem to be incomplete: Sonerezh can't find the cover in the metadata and uses "no-cover.png" instead.

**Comment by Knah-Tsaeb** [comment]
Maybe add function for test existing cover in folder with most common name (cover.*, front.*).

**Comment by nodiscc** [comment]
Files commonly used as thumbnails in directory-based music browsers are `folder.{jpg,png}`, `cover.{jpg,png}`, `front*.{jpg,png}`, `.mediaart/*.{jpg,png}` and `.mediaartlocal/*.{jpg,png}`

**Comment by lGuillaume124** [comment]
Yes, this is an interesting feature, we will work on it.

**Comment by mirtouf** [comment]
I confirm a nice feature would be to let the user choose its own fanart for each of its album or to program automatic search inside the application.

**Comment by tomcodes** [comment]
It might also be interesting to use Discogs API to get album artwork if you don't get one locally:

* whether automarically
* whether manually for each album by inserting the master release URL

**Comment by nodiscc** [comment]
Musicbrainz also has an API for cover art (https://wiki.musicbrainz.org/Cover_Art_Archive/API) and their collection is _very_ exhaustive.

However if something like that is fetched from third-party websites, it has to be optional. People may not want the app to leak theire whole music collection to a third-party.

**Comment by tomcodes** [comment]
@nodiscc agreed. I'd be interested in working on that feature!

**Comment by onno-vos-dev** [comment]
I Just want to add to this discussion that even though musicbrainz currently does not have an API limit, I would be careful with firing thousands, tens of thousands or even more requests their way as a limit could very quickly be implemented then.

Might be good to keep this in mind in order not to hammer their servers once this feature is implemented.

**Comment by nodiscc** [comment]
Yes. I think this issue should be retitled "use local files as coverart". It's a simpler step, and there are other tools to fetch covers from web services.

**Comment by lGuillaume124** [comment]
We will not call third-party API to consolidate the metadata during the import process because it will cause too many calls (imagine if you have tens of thousands songs...).

BUT, we could imagine a little button "Auto-complete" on the metadata edition form, which could request MusicBrainz and try to auto-complete the song metadata.

**Comment by nodiscc** [comment]
> little button "Auto-complete" on the metadata edition form

Is there a metadata edition form already?

**Comment by lGuillaume124** [comment]
> Is there a metadata edition form already?

Not yet :)

**Comment by nodiscc** [comment]
Ok so this issue is in fact 3 issues:

 * Use local image files as cover art
 * Add song metadata edition form and capabilities
 * Fetch song metadata from third party APIs

You may want to split this bug report in 3 new issues. One of these is probably simpler to solve :)

**Comment by FoxiesCuties** [comment]
I have to encounter a problem with the thumbnails
http://www.hostingpics.net/viewer.php?id=600165problem.jpg

because the link is 
"/img/thumbnails%5Ca99b4f08bc0bdeacd57aaae30e58882a_220x220.jpeg"
instead
"/img/thumbnails/a99b4f08bc0bdeacd57aaae30e58882a_220x220.jpeg"

"/" is replace with "%5C" i solved this with

<VirtualHost *:80>
...
	AllowEncodedSlashes On
...
</VirtualHost>

maybe WampServer ( Win64 ) cause this.

I really like our project, good job for the cleary design

**Comment by FoxiesCuties** [comment]
I encounter a "backslash problem" on firefox on the thumbnail aside player

http://www.hostingpics.net/viewer.php?id=402901alone.jpg

```
src="\img/thumbnails\3cfb1a2f13b229a2567c65a7fa17653d_64x64.jpeg"
```
firefox no understand the backslash i try some plugin like :

https://addons.mozilla.org/fr/firefox/addon/slashy/
or
https://addons.mozilla.org/fr/firefox/addon/backslash-to-forward-slash

but appear no effect on my problem

Only firefox cause problem for me, i fix this like that

i modify the file

```
app\webroot\js\player-nav.js
```

```
$('.song-cover').attr('src', track.cover.replace(/(\.[a-z0-9]+)/i, "_64x64$1"));
```

```
$('.song-cover').attr('src', track.cover.replace(/\\/, '/').replace(/(\.[a-z0-9]+)/i, "_64x64$1"));
```


Sorry for double post, i just want separate my two problems
