### ISSUE TITLE
Enhancement : ability to add multiple music folders in a database

### ISSUE THREAD

**Issue by GLLM** [Sonerezh/sonerezh#61]
Hey,

I though it'd be good if we could use several folders in a database.
My library is splitted in 2 folders, not located in the same folder ...
Maybe we could do so, separating the path with c comma or semi-colon ?

Any opinion ?

Keep up the good work guys :)
GLLM

**Comment by nodiscc** [comment]
@GLLM Have you tried symlinks or `mount --bind` to setup a common directory? in `/etc/fstab`:

    /path/to/music1 /path/to/sonerezh/library none bind
    /path/to/music2 /path/to/sonerezh/library none bind

**Comment by GLLM** [comment]
No, I did not.
I'm based on a Synology NAS. I could indeed put my hand sin the system, but if Sonerezh could allow it, it'd be much more convenient :)

**Comment by lGuillaume124** [comment]
That would not be very complicated to implement.
