### ISSUE TITLE
database vide

### ISSUE THREAD

**Issue by smokinsiouxx** [Sonerezh/sonerezh#62]
bonjour,

Je l'ai installé sur mon ubuntu server 14.04 en suivant le tuto à la lettre, mais j'ai un léger problème...
Ma database est empty.
J'ai monté mes fichiers de musique via fstab et ça ne fonctionne pas. Y a t'il une restriction de ce côté ?

j'imagine qu'il y a une sombre histoire de droits derrière tout ça mais je n'arrive pas à trouver la solution à mon problème.

quelqu'un aurait il une idée ou une piste pour résoudre ce problème ?

**Comment by lGuillaume124** [comment]
Bonjour,

Auriez-vous des messages d'erreur ou des logs à nous fournir svp ?
