### ISSUE TITLE
Any instruction on how to install this on a mac?

### ISSUE THREAD

**Issue by nshung** [Sonerezh/sonerezh#64]
I am having trouble with getting this up on Mac. I have already installed cakephp, enable php and mod_rewrite and set up a mysql database too. But I think I need to do something with apache configuration. 

I tried to put the apache configuration from https://www.sonerezh.bzh/docs/en/annexes.html into my apache httpd.conf file, servername to localhost and changed directory to /Library/WebServer/Documents/ in Directory. But I still cannot run the application when I go to localhost/sonerezh. It just does not load and does not show any error either. Just a blank page.

Any help is appreciated.

**Comment by nshung** [comment]
I got it up and running but stuck on installation page. The error is "Unable to save your data". Just that. 

Database is populated with a table though.

**Comment by nodiscc** [comment]
@nshung First step is to check your web server and MySQL access/error and make sure you've set correct rw permissions for the sonerezh directory. Please post relevant error messages as well as the complete name and version numbers of your server stack (apache/mysql/php) and possible messages in your browser console

**Comment by nshung** [comment]
Apache Server Verion: 2.4.9 (Unix)
PHP version: 5.5.14

I have the follow code in Apache httpd.conf file.

```
<Directory "/Library/WebServer/Documents/sonerezh">
        Options -Indexes
        AllowOverride All

        #Apache 2.2.x
        <IfModule !mod_authz_core.c>
            Order Allow,Deny
            Allow from all
        </IfModule>

        #Apache 2.4.x
        <IfModule mod_authz_core.c>
            Require all granted
        </IfModule>
</Directory>
```
On the install page, I have filled out all the necessary information like database name, username, password etc.. It seems like the script is able to access the database because it created a table in my database name called sonerezh.

But when I click on 'Run', I got an error message at the top that said, "Unable to save your data". The image link below is what the error looks like.

http://i.imgur.com/0ZiyYft.png

**Comment by pikzen** [comment]
This means that Sonerezh wasn't able to write to database either your email/password combo or your settings. Are you sure that your MySQL user has the appopriate rights to write data ?

`GRANT ALL ON sonerezh.* TO '<user>@localhost';`

**Comment by nshung** [comment]
yeah. My mysql user has the appropriate rights to write data to database.
take a look at this. 

![](http://i.imgur.com/s4VeDsb.png)

**Comment by lGuillaume124** [comment]
Thanks all for your help :)
What do you have in app/tmp/logs/error.log?

**Comment by nshung** [comment]
Nothing there. There is no 'error.log' file in that directory. But a file name called 'empty' without any file extension.

**Comment by lGuillaume124** [comment]
Following your screenshots the error happens because Sonerezh is unable to save the user account informations. You must use a valid email address as login and a password which contains at least 8 characters.

**Comment by nshung** [comment]
But I used a real email address and password that is longer than 8 character and includes both upper, lower and number.

**Comment by nodiscc** [comment]
Sorry I accidentally a word in my previous comment:

what's in your apache and mysql error logs? On Debian they can be found at `/var/log/mysql.err` and `/var/log/apache2/access.log` and `/var/log/apache2/error.log`.

A possible workaround would be running your server in a VM.

**Comment by nshung** [comment]
```
[Tue Mar 17 23:54:43.015538 2015] [mpm_prefork:notice] [pid 6092] AH00169: caught SIGTERM, shutting down
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using Brangs-MacBook-Pro.local. Set the 'ServerName' directive globally to suppress this message
[Tue Mar 17 23:54:43.813140 2015] [mpm_prefork:notice] [pid 6142] AH00163: Apache/2.4.9 (Unix) PHP/5.5.14 configured -- resuming normal operations
[Tue Mar 17 23:54:43.813198 2015] [core:notice] [pid 6142] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
```

**Comment by Knah-Tsaeb** [comment]
Same issue (Unable to save your data) on fresh install under ArchLinux.

The installer create table => yes
The installer set setting => yes
The installer set user => fail

**Comment by FoxiesCuties** [comment]
Try this https://github.com/Sonerezh/sonerezh/pull/68

i encounter the problem on an second installation :(

**Comment by Knah-Tsaeb** [comment]
That work for me. Thanks.

**Comment by FoxiesCuties** [comment]
No problems, your're welcome.

Maybe an admin merge the pull request :)

**Comment by lGuillaume124** [comment]
Done, thanks a lot :)
