### ISSUE TITLE
Artist or album listing not working

### ISSUE THREAD

**Issue by bobgrants** [Sonerezh/sonerezh#67]
Hello,

First of all well done guys for Sonerezh, I have been trying a lot of music streaming service, and yours is by far my favorite. :)

I have setup sonerezh on a Raspberry pi running Xbian, and my music is hosted on a NAS on my home network. 
The install went well, the web interface is a bit slow sometimes but the music is playing loud and clear.

However my problem is that the Artists and Albums page will not load the whole library but only the first 9 rows (36 thumbnails). If I scroll down, sometimes I can see the 4 blue circle showing it is loading but nothing shows up.

If I look for an album/artist manually it works fine, even for an album/artist not displayed, so the library is there and updated properly. In the settings I can see that all my songs are there. and the album / artist count seems right.

I have cleared the cache but nothing is working. Any ideas ?

**Comment by nodiscc** [comment]
Hi, do you see any messages in your web server logs or browser console? What software/versions are you using?

**Comment by lGuillaume124** [comment]
Hi, thanks for your feedback :)

Like nodiscc said: what is your browser please?

**Comment by bobgrants** [comment]
Hi !

The console is not showing anything, however I have this line in the error log :

[Fri Mar 20 12:02:24 2015] [error] [client 217.75.2.210] Invalid method in request JSON /sonerezh/songs/artists/page:2/sort:Song.band/direction:asc?ajax=true HTTP/1.1, referer: http://xxx.com:1234/sonerezh/artists

Software version list : 

Sonerezh v0.9.0-beta
Apache2 : 2.2.22-13
php5 : 5.4.36
mysql : 5.5.41-0


I'm using mainly Chrome Version 41.0.2272.89 m
I just tried with Internet Explorer 11.0.13 and with this one, I can't navigate. I see the loading bar at the top but nothing happens when I click the menus
Firefox 35.0.1 is the fastest of all, but I have the same issue, can't browse the music

Let me know if I forgot something

**Comment by atomiix** [comment]
Hi !
I think your problem is now fixed on the 1.0.0-beta branch since the PR #82 was merged :)

I'll close this issue but let me know if it's not good for you.
