### ISSUE TITLE
Shuffle on all titles (or albums ?)

### ISSUE THREAD

**Issue by emengd** [Sonerezh/sonerezh#69]
Hi,

Correct me if I am wrong, but it seems to me that it is currently impossible to shuffle through the whole library from the interface. That would be a pretty nice feature, and one that most music players offer.

A special playlist "all" would be one way to make this work, though you could also have a dedicated icon, or a "add all to queue" button.

Probably a tad more complicated to implement, but shuffling through all albums would also be cool (and shuffling through a selected set  of albums even better).

**Comment by nodiscc** [comment]
Duplicate of https://github.com/Sonerezh/sonerezh/issues/47 ?

**Comment by emengd** [comment]
Oh, sorry, I hadn't seen that one.

**Comment by lGuillaume124** [comment]
This functionality is a big headache, but essential ^^

**Comment by Niols** [comment]
Randomly pick one album could already be something cool and maybe easier to implement ?

**Comment by nodiscc** [comment]
@lGuillaume124 Keeping duplicate issues open may lead to brain injury. Just sayin for your own sake.

**Comment by lGuillaume124** [comment]
Yes, sorry ^^
