### ISSUE TITLE
Gestion des disques sur les fichiers OGG

### ISSUE THREAD

**Issue by lGuillaume124** [Sonerezh/sonerezh#7]
Les albums contenant plusieurs disques au format OGG ne seraient pas bien triés.

**Comment by tap3** [comment]
Salut, je sais pas si c'est le même problême que moi. Si non j'ouvrirais un autre thread.

Ma Musicothèque est en OGG proprement taggué. Mais lorsque je prends un album, il est classé par ordre Alphabétique et non par numéro de chanson ! Et les pochettes ne s'affiche pas. J'ai vérifié avec du FLAC et du MP3 ça marche très bien.

Merci à l'équipe Sonerezh et aux contributeurs du projet pour ce bijoux :)

**Comment by lGuillaume124** [comment]
Salut,

Merci pour le retour. Pourrais-tu nous faire parvenir quelques chansons posant problème ?

**Comment by tap3** [comment]
Salut, désolé pour la réponse tardive. 
Bien sur je peut te faire parvenir un album, indique moi juste comment ?  

Merci

**Comment by lGuillaume124** [comment]
Envoie-nous un mail à hey@sonerezh.bzh je vais te fournir un lien vers un outil pour que tu puisses nous envoyer ta musique.

**Comment by yabb85** [comment]
Bonjour

J'ai également le problème, les numéros de pistes ne sont pas pris en compte sur les fichiers ogg.
Sur les fichier flac les numéros sont pris en compte mais pas affiché.
J'utilise la branche master pour le moment je vais essayé d'installer la version bêta afin de voir si les problèmes existent toujours.

**Comment by lGuillaume124** [comment]
Bonjour,

Peux-tu nous envoyer un ou plusieurs fichiers OGG posant problème stp ?
hey@sonerezh.bzh

Merci ;)

**Comment by lGuillaume124** [comment]
Merci @yabb85 j'ai pu identifier d'où venait le problème :)
