### ISSUE TITLE
FLAC files don't play, page just reloads

### ISSUE THREAD

**Issue by nodiscc** [Sonerezh/sonerezh#70]
Same symptoms as #53. When I click on "play" next to certain songs, the page just reloads and nothing is played. The songs are FLAC files that are correctly indexed by sonerezh:

```
[search for music]
[click on play icon next to a song, or next to an album]
00:19:04.555 GET https://my.server.org/music/songs/ajax_view/9786 [HTTP/1.1 200 OK 24ms]
00:19:04.613 GET https://my.server.org/music/songs/download/9786 [HTTP/1.1 404 Not Found 119ms]
00:19:04.614 GET https://my.server.org/music/img/no-cover_64x64.png [4ms]
[ page gets reloaded ]
00:19:04.733 GET https://my.server.org/music/search [HTTP/1.1 200 OK 62ms]
```

Note the 404 error. All codec checkboxes are green on https://html5test.com/, FLAC test reports "unsupported" on http://hpr.dogphilosophy.net/test/. This happens on Firefox 36.0.1 on Windows 7 and Ubuntu. 

Are you able to play FLAC files in sonerezh? Are you able to play this file http://hpr.dogphilosophy.net/test/flac.flac in your browser? Not having FLAC support is a major pain, is there any workaround to this?

**Comment by lGuillaume124** [comment]
Do you have automatic tracks conversion enabled?

**Comment by nodiscc** [comment]
No. (I have no interest in enabling it because converting all my FLAC files to mp3 would result in very high disk space usage - 2 copies of each track, unless the conversion process overwrites my FLAC files with mp3s? which would be also bad. There's no doc on this, I don't know where it's supposed to store converted files).

I'm confused, is this a browser audio format support problem? Or is this a problem on sonerezh (why the 404 error?)

I have not been able to find a bug report on firefox's bug tracker regarding FLAC playback. On Linux audio codecs are provided by gstreamer, which supports flac, so it should work fine borwser-side. I'll do more tests, but I think the 404 error is a bug on the app side.

**Comment by lGuillaume124** [comment]
In fact, when Sonerezh detects a FLAC file, it tries to convert it to MP3 or OGG (depending on your settings) using avconv to app/tmp/.

In your case, when you request `/songs/download/9786`, Sonerezh returns an MP3 file that it was unable to create because you have disabled the auto-conversion. That's why the 404 error is raised.

We know we need to improve this part of Sonerezh, the best should be on-the-fly conversion (without any cache) but we did not succeed to deal with it yet...

**Comment by nodiscc** [comment]
Thanks for your reply,

1. in my case it is not possible to convert FLAC files to ogg/mp3 because it would make my `/var/` partition explode (unless you make the conversion output dir configurable instead of the hardcoded `app/tmp`)

2. Ok, now I understand why it raises a 404 error. Note that having these songs displayed in the track list is confusing, since they are actually not there when conversion is disabled. I suggest you defer indexing them _after_ the actual conversion has been made, so i doesn't raise a mysterious error.

3. Is it possible to _not_ convert FLAC files and have sonerezh try to play them directly? If the format is not supported by the browser (I think it should be, as I said above), well we can always report a bug to mozilla about supporting FLAC files playback.

What do you think?

**Comment by AugierLe42e** [comment]
> Is it possible to not convert FLAC files and have sonerezh try to play them directly? If the format is not supported by the browser (I think it should be, as I said above), well we can always report a bug to mozilla about supporting FLAC files playback.

I'd like that too. My 1To music library is almost only FLAC, I'll never have enough space on my server :smile:

**Comment by nadley** [comment]
Hi all,
I'm also interrested about a flac support without conversion, as I'm only using FLAC.

I found this about a browser side flac decoder in Javascript may be it can be use to be a starting point for something: https://github.com/audiocogs/flac.js/tree/master .

Thanks regards

**Comment by lGuillaume124** [comment]
Hi,

We have already tried to implement the flac.js library in the past, but the result was not good enough.
As an increasing proportion of users ask us to decode FLAC on the fly, we will try again, but not for the 1.0.0 release because it requires too much work :)

What do you think @atomiix ?

**Comment by nadley** [comment]
@lGuillaume124 No problem, I think we can all wait a little bit. And for me I totaly understand that you want to release something stable for the 1.0.0 ;-)

If you have idea about how you plan to decode FLAC on the fly, I think you can share it here so we can gave our opinion to find the best solution no ? Because it look like it is something quite complex for the moment :-(
