### ISSUE TITLE
Problème à l'import.

### ISSUE THREAD

**Issue by Niols** [Sonerezh/sonerezh#71]
Bonjour,

Super job, j'utilise Sonerezh depuis quelques jours, et je suis vraiment conquis.

J'ai quand même un bug étrange : j'ai [un album](http://rnd.niols.net/Wolfgang%20Amadeus%20Mozart%3b%20Ingrid%20Schmith%c3%bcsen,%20Catherine%20Patriasz,%20Neil%20Mackie,%20Matthias%20H%c3%b6lle,%20La%20Petite%20Bande,%20Nederlands%20Kamerkoor,%20Sigiswald%20Kuijken.tar.gz) qui est importé **à chaque fois que je met à jour la base de données**.

- un caractère interdit dans les noms / les tags ?
- un nom / un tag trop long ?

Je surveille l'issue s'il y a des questions.

**Comment by Niols** [comment]
En fait, j'ai un peu plus précis :
Les deux premières musiques de l'album (l'Introitus et le Kyrie) ne sont pas ré-ajoutés à chaque mise-à-jour. Toutes les autres le sont.

**Comment by FoxiesCuties** [comment]
Hello,

The rootpath couldn't exced 255 characters so you must rename 

from
```
Wolfgang Amadeus Mozart; Ingrid SchmithÃ¼sen, Catherine Patriasz, Neil Mackie, Matthias HÃ¶lle, La Petite Bande, Nederlands Kamerkoor, Sigiswald Kuijken
```
to

```
Wolfgang Amadeus Mozart
```

**Comment by Niols** [comment]
Why is there such a limit ?

**Comment by FoxiesCuties** [comment]
Vous pouvez faire ceci au pire

```
ALTER TABLE `songs` CHANGE `source_path` `source_path` VARCHAR(XXX) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
```
XXX une valeur supérieur à 255

EXEMPLE :
```
ALTER TABLE `songs` CHANGE `source_path` `source_path` VARCHAR(300) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
```

**Comment by Niols** [comment]
Je vois, ça vient de la base de données. Il n'y a pas moyen de tester la déjà présence d'un album seulement aux 255 premiers caractères ? Ca éviterait ce genre de petit problèmes ?

**Comment by FoxiesCuties** [comment]
Je ne pourrais vous répondre a ce sujet peut être qu'une personne plus qualifié vous répondra.

**Comment by Niols** [comment]
D'accord. Merci beaucoup pour votre réponse, ça règle mon problème au moins temporairement.

**Comment by lGuillaume124** [comment]
On va revoir cette partie là pour la prochaine version, en lien avec l'issue #61. La limite de 255 caractères sera levée et il sera possible d'ajouter plusieurs dossiers source.
