### ISSUE TITLE
Support des caractères spéciaux

### ISSUE THREAD

**Issue by Niols** [Sonerezh/sonerezh#72]
J'ai un problème avec certains caractères spéciaux (comme œ).

Les chansons sont affichées avec un ? (« Tais toi mon c?ur »). Mais je ne pense pas que le problème vienne de l'affichage, parce que je peux chercher « c?ur » et trouver toutes les chansons concernées. J'imagine donc que ça vient de la phase d'import des musiques.

**Comment by mneute** [comment]
J'ai le même soucis.
Il s'agit effectivement d'un problème à l'import, puisqu'en base de données, j'ai ceci : "Le C?ur qui cogne".

**Comment by lGuillaume124** [comment]
Bonjour,
Pourriez-vous nous faire parvenir vos pistes qui recontrent ces problème svp ? Contactez-nous par email à hey@sonerezh.bzh on vous indiquera où envoyer vos fichiers.

Merci !

**Comment by lGuillaume124** [comment]
Le problème vient de l'encodage utilisé pour les tags ID3v1 (ISO 8859-1) qui ne supporte pas les caractères spéciaux (le œ notamment). En fait Sonerezh ne récupère juste pas la bonne valeur...

![selection_008](https://cloud.githubusercontent.com/assets/3330841/6823462/94b06180-d2e8-11e4-8862-f9e0fdd26340.png)

La première ligne correspond au tag ID3v1, la deuxième au tag ID3v2 (encodé en UTF-16, caractères spéciaux supportés donc) et Sonerezh récupère... la première ligne.

**Comment by Niols** [comment]
Est-il prévu que cela change ?
Il pourrait être cohérent de chercher à utiliser les tags ID3v2 s'ils sont présents, et les tags ID3v1 sinon, il me semble. Mais je ne sais pas vraiment quels sont les usages.

Question non liée à cette issue : qu'utilisez vous pour visualiser les tags de cette manière ?

**Comment by lGuillaume124** [comment]
Oui je suis en train de corriger cela.

Cette vue est obtenue avec les scripts de démo de la lib getID3 (http://www.getid3.org/).

**Comment by Niols** [comment]
Merci beaucoup, je vous laisserai fermer l'issue alors.
Très beau travail en tous cas !

**Comment by lGuillaume124** [comment]
Corrigé :)

![selection_009](https://cloud.githubusercontent.com/assets/3330841/6823891/cd960d5c-d2ec-11e4-9938-187eedfb008a.png)
