### ISSUE TITLE
Bloqué lors de l'installation.

### ISSUE THREAD

**Issue by WOoOinux** [Sonerezh/sonerezh#76]
Bonjour,

Tout d'abord, bravo pour ce soft, j'ai testé la démo et j'en suis ravi :)

J'ai entrepris d'installer Sonerezh sur mon serveur dédié et je suis confronté à un problème lors de l'installation. En effet, j'arrive bien sur la page http://mon-domaine.tld/install et peux remplir les champs mais lorsque je clique sur "Run" alors on me propose de télécharger le fichier "install".

J'ai cherché sur différents forums et ai compris que c'était très certainement les fichiers htaccess de cakephp qui n'étaient probablement pas correctement configurés.

**Voici mon virtualhost :**

<VirtualHost *:80> 
        ServerAdmin webmaster@localhost 

        ServerName mon-domaine.tld  

        DocumentRoot /home/user/public_html/sonerezh
	SuexecUserGroup user user
 
        <Directory /> 
                Options FollowSymLinks 
                AllowOverride All 
        </Directory> 
        <Directory /home/user/public_html/sonerezh/> 
                Options Indexes FollowSymLinks MultiViews 
                AllowOverride All 
                Order allow,deny
		allow from all
        </Directory> 

        ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/ 
        <Directory "/usr/lib/cgi-bin"> 
                AllowOverride None 
                Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch 
                Order allow,deny
                Allow from all 
        </Directory> 

        ErrorLog ${APACHE_LOG_DIR}/error.log 

        # Possible values include: debug, info, notice, warn, error, crit, 
        # alert, emerg. 
        LogLevel warn 

        CustomLog ${APACHE_LOG_DIR}/access.log combined 

</VirtualHost>

**Ainsi que le fichier root/.htaccess :**

<IfModule mod_rewrite.c>
   RewriteEngine on
   RewriteBase /
   RewriteRule    ^$ app/webroot/    [L]
   RewriteRule    (.*) app/webroot/$1 [L]
</IfModule>

**Le fichier root/app/.htaccess :**

<IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteBase /app
    RewriteRule    ^$    webroot/    [L]
    RewriteRule    (.*) webroot/$1    [L]
</IfModule>

**Et enfin le fichier root/app/webroot/.htaccess :**

<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /app/webroot
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^(.*)$ index.php [QSA,L]
</IfModule>

Je précise enfin que le mode rewrite est bien activé car je l'utilise déjà pour d'autres sites.

Il doit me manquer quelque chose mais quoi ?
Une idée ?

D'avance merci pour votre aide.

Geekialement,
WOoOinux

**Comment by nodiscc** [comment]
As tu activé mod php?

**Comment by WOoOinux** [comment]
Bonsoir et merci pour ta réponse.

Voici ce que me donne apachectl -M

Loaded Modules:
 core_module (static)
 log_config_module (static)
 logio_module (static)
 mpm_prefork_module (static)
 http_module (static)
 so_module (static)
 alias_module (shared)
 auth_basic_module (shared)
 authn_file_module (shared)
 authz_default_module (shared)
 authz_groupfile_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 cgi_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 headers_module (shared)
 include_module (shared)
 mime_module (shared)
 negotiation_module (shared)
 reqtimeout_module (shared)
 rewrite_module (shared)
 setenvif_module (shared)
 ssl_module (shared)
 status_module (shared)
 suexec_module (shared)
** suphp_module (shared)**
 userdir_module (shared)

En fait j'utilise suphp donc dans mon cas c'est le suphp_module qui prend la place.

Geekialement,
WOoO

**Comment by lGuillaume124** [comment]
Bonjour,

Merci pour les retours et les compliments :)
Visiblement il s'agit d'un problème de configuration de votre côté et non d'un problème de Sonerezh en elle-même. Ne connaissant pas suphp je ne vais pas pouvoir vous aider...

Par contre il me semble que la valeur ``RewriteBase`` de vos fichiers .htaccess devraient plutôt être de la forme ``/home/user/public_html/sonerezh/app``

**Comment by WOoOinux** [comment]
Bonjour et merci pour votre réponse,

Oui je suis bien concient que le problème ne vient pas de votre application mais bien d'une configuration côté serveur et je vous remercie d'autant plus d'essayer de m'aider ;) 

Je vais tester la modification de RewriteBase dans le fichier que vous m'avez dis et reviendrai poster un retour.

Comme je le dis, Sonerezh n'est pas en cause mais si d'autres personnes rencontrent un problème de configuration serveur çà sera toujours bien d'avoir une éventuelle solution ici même ;)

Geekialement,
WOoOinux

**Comment by lGuillaume124** [comment]
Bonjour @WOoOinux 
Toujours embêté lors de l'installation ?

**Comment by WOoOinux** [comment]
Bonjour @lGuillaume124 
Désolé je n'ai pas fait de retour...
Maleureusement la modification de RewriteBase n'a rien donné. J'ai abandonné les recherches pour le moment et re-testerai plus tard car je suis toujours intéressé par votre application. J'espère pouvoir trouver le bon réglage d'Apache la prochaine fois.
Encore merci pour votre aide.

**Comment by lGuillaume124** [comment]
Pas de réponse depuis mai 2015, je me permets de fermer cette demande.
