### ISSUE TITLE
Definition VENDORS

### ISSUE THREAD

**Issue by cc2i** [Sonerezh/sonerezh#77]
sur lib/Cake/bootstrap.php
à la ligne 110
```php
/**
 * Path to the vendors directory.
 */
if (!defined('VENDORS')) {
	define('VENDORS', ROOT . DS . 'vendors' . DS);
}
```
Il n'y a  pas de d'éléments correspondant à ce chemin
ne devrait pas plutôt pointer  sur APP . 'Vendor'  

Normal ?

**Comment by lGuillaume124** [comment]
Bonjour,

Vous êtes dans le code source de CakePHP là... Et cette ligne est tout à fait normale : http://book.cakephp.org/2.0/fr/getting-started/cakephp-folder-structure.html

C'est juste que comme nous n'avons pas de 'Vendors'.

**Comment by cc2i** [comment]
Ok Merci pour cette précision...
