### ISSUE TITLE
Use local image file as cover art

### ISSUE THREAD

**Issue by lGuillaume124** [Sonerezh/sonerezh#78]
Inspect album folder on import to find cover

**Comment by lGuillaume124** [comment]
Here is a list of file names Sonerezh can look for:

* ``folder.{jpg,jpeg,png}``
* ``cover.{jpg,jpeg,png}``
* ``front*.{jpg,jpeg,png}``

**Comment by nodiscc** [comment]
Please consider making this list case-insensitive, thanks!

**Comment by PiXELART** [comment]
@lGuillaume124 U should also use the dirname ;)

**Comment by lGuillaume124** [comment]
@PiXELART what do you mean?

**Comment by PiXELART** [comment]
For example, i have IAM-Platinum-FR-3CD-FLAC-2005-Mrflac as dirname, u can looking for IAM-Platinum-FR-3CD-FLAC-2005-Mrflac.{jpg,jpeg,png}

**Comment by lGuillaume124** [comment]
Ok we could test it
