### ISSUE TITLE
Last.fm support

### ISSUE THREAD

**Issue by sardaukar** [Sonerezh/sonerezh#83]
Any plans to support Last.fm integration?

**Comment by fcharlier** [comment]
:+1: Last.fm and Libre.fm integration would be great !

**Comment by bondneverdies** [comment]
+1 for this feature request

**Comment by tap3** [comment]
:+1:

**Comment by PiXELART** [comment]
Could be an awesome future!

**Comment by fcharlier** [comment]
I proposed a Sonerezh connector in david-sabata/web-scrobbler#884 which allows scrobbling songs when using the extension in Chromium-based browsers.
The url filter might have to be updated depending on specific installations (can be done in the extension preferences)

**Comment by lGuillaume124** [comment]
Thanks a lot for your contribution :)

**Comment by fbardel** [comment]
+1 background artist or album with Last.fm will be great to dress (?) the app ;) thanks !!

**Comment by nodiscc** [comment]
@fbardel I think this issue is about [scrobbling](https://www.urbandictionary.com/define.php?term=Scrobble), not fetching album/artistart.

**Comment by fbardel** [comment]
Yes indeed (-_-)

**Comment by MJuma** [comment]
👍
