### ISSUE TITLE
Why not use composer?

### ISSUE THREAD

**Issue by veloxy** [Sonerezh/sonerezh#85]
I don't understand why you are committing libraries, why not use composer?

DebugKit, CakePHP and GetID3 are all available through composer..

**Comment by nodiscc** [comment]
The current method has the advantage of providing an app installable with `git clone`, no need to run `composer update` (some hosts do not provide command line access...). Maybe a Makefile to make sure the libraries are up to date with upstream would be good though

**Comment by veloxy** [comment]
How would you do a git clone on a host without command line access in the first place?

You could always make releases with the vendor files included, I think github allows you to zip a whole project and upload it (for the people who just want to upload files to a server). 

https://help.github.com/articles/creating-releases/
