### ISSUE TITLE
Compilations

### ISSUE THREAD

**Issue by isosk8** [Sonerezh/sonerezh#87]
Bonjour,

Comment sont gérées les compilations dans l'application ?
Elles apparaissent "Artist" et dans "Album".
Dans ce dernier il considère autant d'album que d'artist différents.

**Comment by nodiscc** [comment]
Il faut que tes fichiers soient taggés avec la même valeur pour `Band`. Voir https://github.com/Sonerezh/sonerezh/issues/30

**Comment by isosk8** [comment]
Merci pour cette réponse rapide.
Le tag ne peut pas se faire directe dans sonerezh ? Il faut une application tierse ?

**Comment by nodiscc** [comment]
> Le tag ne peut pas se faire directe dans sonerezh ? 

Non. https://github.com/Sonerezh/sonerezh/issues/79

Je conseille musicbrainz picard ou exfalso sous linux, ou mp3tag si tu es sous windows.

**Comment by isosk8** [comment]
Merci

**Comment by nodiscc** [comment]
De rien; pense à fermer ce bug et à surveiller #79
