### ISSUE TITLE
Party time: play random songs / albums

### ISSUE THREAD

**Issue by fcharlier** [Sonerezh/sonerezh#88]
It'd be nice to have a "rolling random playlist" feature to just be able to play some random indefinitely.

Ideas about the feature:
- play random songs
- play random albums
- start with `n` songs/albums, add new songs/albums when there are less than `n` songs in the playlist
- allow to insert other songs/albums and continue random play after

**Comment by peterbrinck** [comment]
Yes please !!!
:+1:  :+1:

**Comment by Niols** [comment]
I think it has already been mentioned in issues https://github.com/Sonerezh/sonerezh/issues/69 and https://github.com/Sonerezh/sonerezh/issues/47.

**Comment by fcharlier** [comment]
@Niols thx, I'll merge my comments in #47 :-)
