### ISSUE TITLE
XSS in playlist

### ISSUE THREAD

**Issue by mephistos** [Sonerezh/sonerezh#89]
Hi,

I see an issue in the playlist management. Possibility to use XSS security breach when you create a playlist.

You can use these name for exemple : 

`XSS</a><script>alert("I CAN DO ANYTHING IN JS !!!!")</script><img src="http://m.memegen.com/5crl1l.jpg" /><a href="/test/">XSS2`

I try it in the demo platform : https://www.sonerezh.bzh/demo/playlists/30

Easy to fix, but that's necessary to look deeper on the whole platform ;)

**Comment by lGuillaume124** [comment]
Hi, thank you for your vigilance :)

**Comment by mephistos** [comment]
Hi, you're welcome ! I have no time to do more :-(

Have a nice debug :)

**Comment by lGuillaume124** [comment]
We had already reviewed the forms but apparently we missed it :/

**Comment by atomiix** [comment]
Hi,

this is an already solved problem (#34) but the demo version is not up-to-date :/

Thanks for your help anyway :)

**Comment by mephistos** [comment]
Yeah good news :-) great job ;-)
