### ISSUE TITLE
Menu avec premiere lettre alphabetique pour les artistes

### ISSUE THREAD

**Issue by fran6t** [Sonerezh/sonerezh#9]
Désolé ça a un nom, mais pas moyen de me le rappeler.
Actuellement quand on clique sur Artists apparait alors la liste des artistes dans l'ordre alphabétique 
et pour aller sur ZZTOP quand nous avons de nombreux d'artistes c'est long.
Je suggère donc un menu horizontal qui permettrait d'afficher la premiere lettre d'un artistes présent, s'il y a pas d'artiste commençant par la lettre B dans ce cas nous aurions A C D le clique sur C filtrerait alors la page qu'avec les artistes commençant pas C

**Comment by lGuillaume124** [comment]
Bonjour,

C'est dans la roadmap (https://www.sonerezh.bzh/docs/fr/roadmap.html) ;)
Ce n'est pas une fonctionnalité si évidente à mettre en place et c'est pourquoi nous avions choisi de ne pas la mettre dans la première bêta. Mais ça viendra !

**Comment by fran6t** [comment]
J'avais pas vu merci, quand il y aura "Édition des métadonnées via l’interface de Sonerezh (méta + pochettes d’albums)" j'abandonnerai definitivement Subsonic.
Je profite de cette issue qui finalement n'a pas lieu d'etre pour demander si a la fin de l'indexation y avait un message de fin. Perso j'ai eu la jauge verte qui a progressé jusqu'au bout, mais pas de popup ou message comme quoi c'etait terminé par contre j'ai pu cliquer et me servir de sonerezh sans pb

**Comment by lGuillaume124** [comment]
Non pas de message particulier, juste la barre qui passe au vert.
Mais la page /import sera refaite en grande partie lorsqu'on ajoutera la possibilité d'envoyer sa musique depuis cette page.
