### ISSUE TITLE
“Prefix (optionnal)” refuses to be let empty

### ISSUE THREAD

**Issue by Niols** [Sonerezh/sonerezh#90]
I just tried to re-install Sonerezh, and I wanted to leave “Prefix (optionnal)” empty (“Leave empty if none”).

It refused to be let empty, and indeed, I found the attribute `required="required"` on this input element.

I suppose it should be easy to fix for anyone knowing how CakePHP works.

**Comment by lGuillaume124** [comment]
This page has been recently modified, I will check this asap ;)

**Comment by Niols** [comment]
I must precise this is only a problem in the generated html page. I removed the `required` attribute by myself and this worked fine.

**Comment by lGuillaume124** [comment]
Yes, and CakePHP sould not generate the ``required`` attribute, following the code:

```php
echo $this->Form->input('DB.prefix', array('placeholder' => __('Leave empty if none'), 'label' => array('text' => __('Prefix (optionnal)'), 'class' => 'col-sm-3 control-label')));
```

**Comment by Niols** [comment]
I just verified, and I'm on 1.0.0-beta. How can I understand why I had this comportment?
