### ISSUE TITLE
Songs are not sorted

### ISSUE THREAD

**Issue by Niols** [Sonerezh/sonerezh#91]
Hello,

I juste cloned the current version of Sonerezh (and discovered the remember me checkbox!), and now my songs and discs aren't sorted anymore.

If this is a general problem, I suppose it should be easy to fix for someone knowing CakePHP.
If not, I'll have to investigate.

**Comment by lGuillaume124** [comment]
Hi,
Could you be more specific please ?

We have redesigned all the sort algorithms for the 1.0.0-beta to be less "database dependant" (because it was done by MySQL in 0.9.0), and we did not encounter any problems. Could you join a screenshot please and describe how it should be sorted?

**Comment by Niols** [comment]
Sorry, I had not my computer at the moment I opened this issue, and then I forgot.

Here is [a picture](https://cloud.githubusercontent.com/assets/5920602/7641774/34352a40-fa8c-11e4-8565-46263e767d72.jpg) of how albums are "sorted" in my Sonerezh's instance.

**Comment by lGuillaume124** [comment]
The problem happens only on the song number?

**Comment by Niols** [comment]
Discs aren't sorted either, since here, disc 2 appears before disc 1.

- In all songs tab, songs are sorted by artist, album, but not songs.
- In artist tab, songs are well sorted.
- In album tab, ... I don't know. It seems not to be sorted by artists.
- Playlists are well sorted.

Do you want images?

**Comment by lGuillaume124** [comment]
Yes I like images :)
I will try to work on Sonerezh next week-end.

**Comment by Niols** [comment]
There they are...

For the songs tab:
![sonerezh_tab_allsongs](https://cloud.githubusercontent.com/assets/5920602/7642197/82f13ee6-fa8f-11e4-94dc-86e21d0840de.jpg)

For the artists tab:
![sonerezh_tab_artists](https://cloud.githubusercontent.com/assets/5920602/7642215/9c3b4f4a-fa8f-11e4-9a81-47ddaf6c4c76.jpg)

My Sonerezh instance seems to be down, so I will wait a bit and edit this comment with my new images asap.
