### ISSUE TITLE
Firefox sous ArchLinux ne fait que rafraîchir la page

### ISSUE THREAD

**Issue by Tangeek42** [Sonerezh/sonerezh#94]
Dès que je suis sur ArchLinux/Firefox, impossible de lire les pistes. Si je clique sur n'importe quel bouton de lecture, la piste en question a l'air de se charger dans le lecteur (le titre devient gras et le lecteur l'affiche), mais ensuite la page est rafraîchie (il suit le lien normalement). Cela ne se produit pas avec Firefox sous Windows, et tous les deux sont à jour (38.0.5). ô_o

Toujours sour ArchLinux, avec Chromium cela **fonctionne** sans problème. J'ai aussi essayé en switchant entre HTTP et HTTPS, mais dans les deux cas j'ai les même résultats, donc c'est pas ça. :/

Je n'ai pas vu d'issue similaire, mais au cas où je l'aurai raté : oups. ^^

(À noter que le problème survient aussi dans le navigateur de la Wii U, donc c'est super-super-urgent. :p )

**Comment by mum1989** [comment]
J'ai le même problème sous Android et sous GNU/Linux avec Firefox (Sonezezh 0.9 beta)

**Comment by atomiix** [comment]
Ça ressemble à un problème de codec, Firefox sous Archlinux ne doit pas avoir de quoi décoder le format de tes pistes tout comme le navigateur de la Wii U.
Peut être une piste : https://wiki.archlinux.org/index.php/Firefox#Multimedia_playback

Tiens nous informés ;)

Pour ce qui est d'Android c'est un [bug connu](https://code.google.com/p/android/issues/detail?id=17553).

**Comment by Tangeek42** [comment]
Mince, alors, ça me serait jamais venu à l'idée de penser "codec". XD Je me sens con, mais ça a marché ! o/
L'option était déjà activée, mais je n'avais pas les dépendances (optionnelles, en fait) de gst. Donc pour ceux intéressés, sous ArchLinux installez les paquets __gst-libav__ et __gst-plugins-good__, et cela devrait fonctionner. :) (Pour le second paquet, j'ai eu énormément d'erreurs 404, mais finalement pacman l'a trouvé dans un autre miroir. Donc ne vous inquiétez pas si ça vous arrive)

Sous Windows j'ai le plugin VLC, donc c'est probablement pour ça que ça fonctionne.
Bref, merci beaucoup !
