### ISSUE TITLE
Pochette Album inexistante

### ISSUE THREAD

**Issue by myke94** [Sonerezh/sonerezh#95]
Bonjour à tous,

J'ai un problème avec les pochettes album qui ne s'affiche pas!
Pourtant, mes albums sont bien taggés.
Une solution pour que ca fonctionne correctement?
Merci

**English version below**

Hi everyone,
I have a problem with the covers which are not dipslayed.
My albums are properly tagged.
Do you have a solution?
Thanks.

**Comment by lGuillaume124** [comment]
Salut,
Sans nous fournir plus d'information, difficile de t'aider :)

Est-ce que les logs Apache te remontent des erreurs ?
